### ISSUE TITLE
Adjust width of the website 

### ISSUE THREAD

**Issue by mohitk30** [QAZIMAAZARSHAD/Movie-Streaming-Website#1]
it contains a large side space that is not necessary at all

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts, then you can start working on this issue.

**Comment by mohitk30** [comment]
Ok,thanks

**Comment by prads46** [comment]
i am new to open source and want to contribute to this issue can u assign me this issue if it is new open?

**Comment by mohitk30** [comment]
> i am new to open source and want to contribute to this issue can u assign me this issue if it is new open?

it is already solved

**Comment by prads46** [comment]
okay no problem thankyou
