### ISSUE TITLE
Add "play now" button when movie card flips

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#10]

**Comment by aum-singhal** [comment]
Hello Sir. I can work on this issue.
If possible, can you assign it to me when LGM-SOC starts

Thanks 😊

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by vishalps2606** [comment]
I would also want to contribute to this issue! Can you assign it to me?

**Comment by QAZIMAAZARSHAD** [comment]
> I would also want to contribute to this issue! Can you assign it to me?

Go ahead,
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Deepak735** [comment]
Hello sir, I would like to work on this issue as an LGMSOC participant..it will be really helpful if you assign it to me...

**Comment by QAZIMAAZARSHAD** [comment]
Remember only the best solution will be accepted.

**Comment by aum-singhal** [comment]
Hello Sir.
I have completed this issue. Can I make a PR today or should I do it tomorrow 🤔
And please also help me with that should I make the PR in the main branch or should create my own first and then make the PR 
in that branch.

Thanks for the help in advance 😊

**Comment by QAZIMAAZARSHAD** [comment]
> Hello Sir.
> I have completed this issue. Can I make a PR today or should I do it tomorrow 🤔
> And please also help me with that should I make the PR in the main branch or should create my own first and then make the PR
> in that branch.
> 
> Thanks for the help in advance 😊

I suggest you to make PR tomorrow because today I have received more than a hundred Github notifications and it will not possible for me to review it today.

And for the other part do whatever you like. Both ways are fine.

**Comment by aum-singhal** [comment]
Okay 😄 No Problem

Thanks for the help 😊

**Comment by MEETOZA123** [comment]
hello sir i can work on this issue
please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> hello sir i can work on this issue
> please assign it to me

This issue has already been resolved and will be closed soon.
Look for any other issues.

**Comment by Deepak735** [comment]
Hello sir i m still working on this issue should i continue it or not

**Comment by QAZIMAAZARSHAD** [comment]
> Hello sir i m still working on this issue should i continue it or not

It is open for you.
But remember only the best solution will be considered.

**Comment by QAZIMAAZARSHAD** [comment]
Add the "Play Now" button below the trailer button.

**Comment by QAZIMAAZARSHAD** [comment]
Only the first and correct PR will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
Add this button on every single movie card.

**Comment by QAZIMAAZARSHAD** [comment]
@aum-singhal, @vishalps2606. @Deepak735, @MEETOZA123 anyone on it?

**Comment by vishalps2606** [comment]
> @aum-singhal, @vishalps2606. @Deepak735, @MEETOZA123 anyone on it?

Yes, I'm on it. But waiting for merging all pull requests. Because if any pull request is merged before mine, some code changes show some conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
@vishalps2606 just make PR, I will merge your first if everything in your PR will be correct.

**Comment by vishalps2606** [comment]
> @vishalps2606 just make PR, I will merge your first if everything in your PR will be correct.

ok

**Comment by saimanoharhm** [comment]
@aum-singhal @vishalps2606 @Deepak735 @MEETOZA123 Any update guys.

**Comment by rompyroshni31** [comment]
Hi Sir, If you could specify that in which respective pages, I'll have to add up the play button when the card flips.
Is it just only on the Movies page or any else too?

**Comment by QAZIMAAZARSHAD** [comment]
> Hi Sir, If you could specify that in which respective pages, I'll have to add up(if I grab this issue) the play button when the card flips.
> Is it just only on the Movies page or any else too?

In every single movie card of every page.
Like home, action, anime, fantasy, etc.

Currently, in kids, web series, and movies page the cards don't have a flip feature so exclude these pages.

**Comment by priyansh11786** [comment]
Hello sir, Can you please elaborate regarding the play now button issue as in If one only needs to display the play now button when the card flips or Is there any additional functionality that one needs to add with it?

**Comment by QAZIMAAZARSHAD** [comment]
> Hello sir, Can you please elaborate regarding the play now button issue as in If one only needs to display the play now button when the card flips or Is there any additional functionality that one needs to add with it?

No just add the PlayNow button below the trailer button.

**Comment by rompyroshni31** [comment]
@QAZIMAAZARSHAD Hey Sir, I would like to work up on this issue. Please assign me this.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Hey Sir, I would like to work on this issue. Please assign me this.

Under DCP or LGMSoC?

**Comment by rompyroshni31** [comment]
Under Devincept(Dcp).

**Comment by rompyroshni31** [comment]
Hello Sir,
Please check this out https://rompyroshni31.github.io/Movie-Streaming-Website/

**Comment by utkarsh-ub** [comment]
> Hello Sir,
> Please check this out https://rompyroshni31.github.io/Movie-Streaming-Website/
> I've added a play button to every flip card present on the pages. Is it okay?

@rompyroshni31 make the play now button similar to the trailer button and also add a play icon before it.Positioning is all right 👍

**Comment by QAZIMAAZARSHAD** [comment]
> Hello Sir,
> Please check this out https://rompyroshni31.github.io/Movie-Streaming-Website/
> I've added a play button to every flip card present on the pages. Is it okay?

@rompyroshni31 one more important thing, your repo is not updated many features are missing.
Before starting to work on any issue always keep your repo up to date.
Fetch upstream.

**Comment by rompyroshni31** [comment]
Hello, Please check it's completed. Sorry for the delay, I had a sessional college test.
https://rompyroshni31.github.io/Movie-Streaming-Website/

**Comment by QAZIMAAZARSHAD** [comment]
> Hello, Please check it's completed. Sorry for the delay, I had a sessional college test.
> https://rompyroshni31.github.io/Movie-Streaming-Website/

check one piece in the anime section.

Your repo is not updated. Fetch upstream.

Check newly updated movies in documentaries, war. and horror page.

**Comment by QAZIMAAZARSHAD** [comment]
Update then make PR.
