### ISSUE TITLE
Improve login page design

### ISSUE THREAD

**Issue by abhijeet141** [QAZIMAAZARSHAD/Movie-Streaming-Website#104]
I would like to enhance the UI of Login Page as keeping in mind the current theme 
Please assign me this issue.

**Comment by ish-0709** [comment]
Sir, I would also like to enhance the UI of the Login Page 
Please assign me this issue. I have recently joined LetsGrowMore.

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD I would also like to contribute to this issue , please assign me

**Comment by ish-0709** [comment]
@QAZIMAAZARSHAD Sir I have linked a PR, please have a look at it and tell me if it's fine or not. Thank you, sir.

**Comment by anushka-srivastava22** [comment]
I am lgmsoc participant. I would love to work upon this issue. Kindly assign me this issue.

**Comment by ish-0709** [comment]
@QAZIMAAZARSHAD Sir I have linked a new PR and solved all the previous issues, added a new sign-up page as well connecting it to the quiz.html page. Please have a look and tell me if the new PR needs any changes?? Thank You, sir.
