### ISSUE TITLE
Add news and coming soon section

### ISSUE THREAD

**Issue by LegendSumeet** [QAZIMAAZARSHAD/Movie-Streaming-Website#106]
![news and comingsoon](https://user-images.githubusercontent.com/85386116/121640274-5806ef80-caab-11eb-9215-5c5b3d1d2e6d.png)
   
can i get assign to it?

**Comment by QAZIMAAZARSHAD** [comment]
@theSumeetGithub go ahead.

But are you sure this section will look good at the bottom?
Also, follow the theme of the website use red and black color.

**Comment by theSumeetGithub** [comment]
ohk  i wll be making them as per the website theme

**Comment by QAZIMAAZARSHAD** [comment]
@theSumeetGithub are you working on this?

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGMSOC 21

**Comment by aditya687** [comment]
Can I work on this issue? I think it will be really nice by addding news and coming soon section under the movie specifications @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue? I think it will be really nice by addding news and coming soon section under the movie specifications @QAZIMAAZARSHAD

Other issues are already assigned to you first resolve them.

**Comment by Srijan1878** [comment]
Can I work on this issue under LGMSOC? @QAZIMAAZARSHAD
