### ISSUE TITLE
Modal popup message not visible when clicking "Click Here" button 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#11]
Home -> TV = dummy.html

**Comment by Rutikab12** [comment]
Hey, @QAZIMAAZARSHAD I would like to work on this issue as an lgm-soc participant.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Rutikab12** [comment]
Okay

**Comment by Rutikab12** [comment]
Hey @QAZIMAAZARSHAD  can I now work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
@Rutikab12 I don't think there is any need for this feature now because contributors are also designing premium and Tv pages.

A better page is way better than a popup "Site is under construction".

**Comment by Rutikab12** [comment]
Okay. I will Look for another issue.
