### ISSUE TITLE
Improve Contact Page

### ISSUE THREAD

**Issue by AKC068** [QAZIMAAZARSHAD/Movie-Streaming-Website#110]
I request you to not to close this issue as I'm working on it.
And I've some good idea than current contact page.

**Comment by QAZIMAAZARSHAD** [comment]
> I request you to not to close this issue as I'm working on it.
> And I've some good idea than current contact page.

go onn

**Comment by Aditya7494** [comment]
I am lgm participant.
I want to contribute on this issue
