### ISSUE TITLE
Changing Mouse Pointer When Hovering Over Movies

### ISSUE THREAD

**Issue by JatanDudeja** [QAZIMAAZARSHAD/Movie-Streaming-Website#114]
When hovering over movies the cursor remains as it is so it does not look like the the movie is clickable so I will change the default cursor to a pointer(hand mouse pointer).

**Comment by JatanDudeja** [comment]
I would like to work on this please assign this issue to me.

**Comment by MEETOZA123** [comment]
i would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on this issue

Since this is an easy issue I cannot assign it to many participants.

**Comment by GaurPeeyush** [comment]
Hey, I've updated index.html with reference to this issue.
Now the cursor is changing to the pointer when you hover over movies.
Do check it out once.

**Comment by QAZIMAAZARSHAD** [comment]
Open a new issue to add cursor pointer effect in kids and tv page.

**Comment by marizvi** [comment]
I am interested to work on this issue, kindly assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> I am interested to work on this issue, kindly assign it to me

This issue is already closed and other issue already assigned to other.
