### ISSUE TITLE
Adjust or redesign genre navigation bar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#12]
![WhatsApp Image 2021-06-01 at 7 19 41 PM](https://user-images.githubusercontent.com/56196640/120334747-86980400-c30e-11eb-8b00-8628679a770d.jpeg)

Make sure all genre names are in one single line side by side.

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD  i'll would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when the contribution period starts then you can start working on this issue.

**Comment by Sourav61** [comment]
![Capture](https://user-images.githubusercontent.com/70853906/120423792-bd126500-c388-11eb-9709-3a22136c10e6.JPG)

**Comment by Sourav61** [comment]
Is this alright or You want some other changes?

**Comment by QAZIMAAZARSHAD** [comment]
This is almost similar, I don't see any change.

I want all genre names in one single line, so it looks nice. 
Like Home, Movies, Web Series, Kids, navigation bar. See these in one line.

![image](https://user-images.githubusercontent.com/56196640/120425366-ac172300-c38b-11eb-9b42-eef8bc0aad1d.png)

**Comment by Sourav61** [comment]
But comedy is now in one line along with others @QAZIMAAZARSHAD

**Comment by Sourav61** [comment]
I'll try to make Suspense & Thriller and SciFy & Fantasy in one line as well

**Comment by QAZIMAAZARSHAD** [comment]
yes

**Comment by Sourav61** [comment]
![Capture1](https://user-images.githubusercontent.com/70853906/120429682-71b18400-c393-11eb-9232-2442e901659e.JPG)

**Comment by Sourav61** [comment]
Is this fine now @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, nice

But do not make any pull requests now because points will be awarded only for pull requests merged during the contribution period which is starting from 10th June.
Also while making the pull requests don't forget to mention the issue number.

**Comment by Sourav61** [comment]
![Screenshot 2021-06-02 112325](https://user-images.githubusercontent.com/70853906/120430718-0d8fbf80-c395-11eb-9e4b-0d7884753b6f.png)

**Comment by Sourav61** [comment]
But when we are hovering over it ,then it appears like this. Is it okay?

**Comment by QAZIMAAZARSHAD** [comment]
You can improve this issue, there is plenty of time.

**Comment by Sourav61** [comment]
Should i create a new issue for that?

**Comment by QAZIMAAZARSHAD** [comment]
No, since your improvement has not been accepted yet

You can improve your design.

**Comment by Sourav61** [comment]
okk thanks @QAZIMAAZARSHAD sir

**Comment by Sourav61** [comment]
![Capture4 JPG](https://user-images.githubusercontent.com/70853906/120635399-10b8a780-c48a-11eb-9a59-3f69343a485b.png)

**Comment by Sourav61** [comment]
Now hovering problem is solved as well @QAZIMAAZARSHAD

**Comment by Sourav61** [comment]
But I have changed the Font size of text. Is is a Problem for you sir?

**Comment by QAZIMAAZARSHAD** [comment]
It's better than before. Nice!

You can always try to improve.

**Comment by Sourav61** [comment]
Thanks @QAZIMAAZARSHAD

**Comment by Sourav61** [comment]
Should i create a PR now?

**Comment by QAZIMAAZARSHAD** [comment]
No,
After 10th June when I will assign you this issue.

In any open-source event don't make PR's directly if you are not assigned. You might not gain points for your work.

**Comment by Sourav61** [comment]
Okk thanks a lot @QAZIMAAZARSHAD sir

**Comment by rucha0702** [comment]
Can I also work upon this issue?

**Comment by QAZIMAAZARSHAD** [comment]
@rucha0702 I think @Sourav61 has already resolved this issue.

When I will merge @Sourav61's PR and if any error or scope of improvement will be there I will assign you this issue.

**Comment by rucha0702** [comment]
okay

**Comment by MEETOZA123** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue

Already solved.
