### ISSUE TITLE
Google authentication

### ISSUE THREAD

**Issue by heyankit78** [QAZIMAAZARSHAD/Movie-Streaming-Website#120]
It helps user to login by google

**Comment by heyankit78** [comment]
I want to work on this
Please assign me

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead.

**Comment by Shady2320** [comment]
Hi @QAZIMAAZARSHAD, can i work on this?

**Comment by heyankit78** [comment]
@Shady2320 I am working on this!

**Comment by QAZIMAAZARSHAD** [comment]
> Hi @QAZIMAAZARSHAD, can i work on this?

I will assign you if this issue remains unresolved for a few more days.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD Sir I am also interested in this and please let me assign this if it remain unresolved for few days.

**Comment by QAZIMAAZARSHAD** [comment]
Ok @royalleads15

**Comment by shivshankar9** [comment]
I would like to give a try on this issue can u assign to me

**Comment by shivshankar9** [comment]
![Screenshot (195)](https://user-images.githubusercontent.com/69760883/122871154-3e3b9700-d34c-11eb-96aa-e836ad61e1b8.png)
This works needs to add only id setup

**Comment by shivshankar9** [comment]
![Screenshot (200)](https://user-images.githubusercontent.com/69760883/123211170-b2a73f00-d4e0-11eb-8b36-5a724229a0d1.png)
signup button working for signup with google but after sign in not redirecting to home page,

**Comment by QAZIMAAZARSHAD** [comment]
Yaa this is an issue https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/347.

If redirecting to the home page after google login then you can make PR.

**Comment by Akshit42-hue** [comment]
Please assign me this issue under LGM-SOC 21 @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me this issue under LGM-SOC 21 @QAZIMAAZARSHAD

Already assigned.

**Comment by Akshit42-hue** [comment]
> > Please assign me this issue under LGM-SOC 21 @QAZIMAAZARSHAD
> 
> Already assigned.
 I have already started working on it please let me assign this if it remain unresolved for few days.

**Comment by QAZIMAAZARSHAD** [comment]
Everyone remember only the first and correct PR will be accepted.
