### ISSUE TITLE
Add more database(more content)

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Movie-Streaming-Website#126]
Hey @QAZIMAAZARSHAD 
I would like to add more database to it.
If possible please assign it to me.
Thanks

**Comment by QAZIMAAZARSHAD** [comment]
> Hey @QAZIMAAZARSHAD
> I would like to add more database to it.
> If possible please assign it to me.
> Thanks

You want to add more movie cards. Right?

**Comment by Shaishav0507** [comment]
Yes

**Comment by Shaishav0507** [comment]
Can I go ahead ?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I go ahead ?
Yes
Use the same size screenshots.

**Comment by Shaishav0507** [comment]
Ok sure.
