### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Movie-Streaming-Website#127]
Hey @QAZIMAAZARSHAD 
I would like to add favicon to the site.
Thanks.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey @QAZIMAAZARSHAD
> I would like to add favicon to the site.
> Thanks.

This issue is already open #9.

Before opening any issue always review that no other similar issue is open.
And first try to solve the issues for which you are already assigned, once complete then go for other issues.
