### ISSUE TITLE
Add links to the following gifs

### ISSUE THREAD

**Issue by Umesh-01** [QAZIMAAZARSHAD/Movie-Streaming-Website#134]
I think these two gifs (see the below image) should contain a links to the related files because there are the chances that anyone can click on them and these are of no use. So it must redirect us to the pages where these files are present. 🙂 
 
![image](https://user-images.githubusercontent.com/83420185/121730446-5241f600-cb0d-11eb-89b6-a31494b88b33.png)

**Comment by Umesh-01** [comment]
@QAZIMAAZARSHAD may I work on this?? 🙂

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21,   Could you please assign this issue to me?

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

Already closed.
