### ISSUE TITLE
Add Top Regional Hits page 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [QAZIMAAZARSHAD/Movie-Streaming-Website#141]
Hello @QAZIMAAZARSHAD sir, I would like to add a page called regional hits just like horrors, comedy etc in that page I will add movies which are top hits and famous movies of different languages like Marathi, gujarati, etc. Please assign this issue to me, I am a LGM-SOC'21 Participant.

**Comment by QAZIMAAZARSHAD** [comment]
Similar issue is already present https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/36.
