### ISSUE TITLE
Favicon logo missing in Website's logo in Title Bar

### ISSUE THREAD

**Issue by sameer882000** [QAZIMAAZARSHAD/Movie-Streaming-Website#142]

**Comment by ish-0709** [comment]
@QAZIMAAZARSHAD I linked a PR for this issue Please have a look. Thank you, sir.

**Comment by QAZIMAAZARSHAD** [comment]
@ish-0709 this issue is already open #9.

Don't make PR's for those issues for which you are not assigned.

**Comment by ish-0709** [comment]
Okay sir, sorry I'll keep that in mind.
