### ISSUE TITLE
Add serials section like popular, new, fantasy in TV page 

### ISSUE THREAD

**Issue by nik464** [QAZIMAAZARSHAD/Movie-Streaming-Website#147]
Hey @QAZIMAAZARSHAD,

I would like to add TV sections page with list of popular tv shows on channels like sony, star plus,colors for our audience. Sir, can you please assign the issue as I am a LGM- SOC participant and will surely complete it by time. Currently it has no list. 
![image](https://user-images.githubusercontent.com/82432273/121774252-32f3a900-cb9f-11eb-8f11-41fe23a1394f.png)

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead.

Add it at the bottom.
It should be similar to other sections with similar effects and features.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Please assign me this issue.

Already assigned to others.
Look for some other issue.

**Comment by QAZIMAAZARSHAD** [comment]
@nik464 are you working on this?

**Comment by QAZIMAAZARSHAD** [comment]
Apart from adding a section correct the movie cards size, flip effect, font size in TV page.

**Comment by saimanoharhm** [comment]
@nik464 Any update ?

**Comment by Sejal2801** [comment]
Assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> Assign it to me

Under DCP or LGMSoC?

**Comment by QAZIMAAZARSHAD** [comment]
@Sejal2801 any updates?

**Comment by ZeTheDeveloper** [comment]
is this repo still active? can you please assign this issue to me?

**Comment by ZeTheDeveloper** [comment]
Hey good day can I know what type of contributions are you looking for? Do I follow the codes according movies, web series & kids?

**Comment by ZeTheDeveloper** [comment]
![image](https://user-images.githubusercontent.com/98612606/183266897-3a73470a-d173-40eb-b593-2a5d9b1d7759.png)
is this what you are looking for?

**Comment by QAZIMAAZARSHAD** [comment]
Fine,

Just make sure the font, color, size and other things should be similar to other pages.
