### ISSUE TITLE
I Want to make search bar functional with a movie API 

### ISSUE THREAD

**Issue by KunalSharmaCoder** [QAZIMAAZARSHAD/Movie-Streaming-Website#150]
``when any people search for a movie It will give all the information about the given movies on a new page through movie API.  you can search any movie on this and it will show all the related  movies according to the search query and all the details like imdb ratings ,etc.`` @QAZIMAAZARSHAD  , can you assign me this issue under LGM-SOC'21.

**Comment by QAZIMAAZARSHAD** [comment]
@KunalSharmaCoder this issue is already open #6.

Before opening any issues make sure that no other similar issue is open.
