### ISSUE TITLE
Enhance TV page

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#156]
I would like to work on this @QAZIMAAZARSHAD Please assign me

**Comment by Kajal-Mishra01** [comment]
Hello @QAZIMAAZARSHAD  

I want to work on this issue please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Hello @QAZIMAAZARSHAD
> 
> I want to work on this issue please assign it to me.

Remember only the best solution will be accepted.

**Comment by Kajal-Mishra01** [comment]
Okay Sir.. Thank You So much

**Comment by Sumit11081996** [comment]
@QAZIMAAZARSHAD please assign me  this issue  to me

**Comment by Srijan1878** [comment]
Can I work on this issue under LGMSOC? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Make TV pages similar to other pages. The flip effect, font everything should be the same.

**Comment by Srijan1878** [comment]
Okay!
