### ISSUE TITLE
Create a movies page

### ISSUE THREAD

**Issue by anushka-srivastava22** [QAZIMAAZARSHAD/Movie-Streaming-Website#163]
Kindly assign this issue to me under lgmsoc . I am a lgmsoc participant and I would loved to contribute to the project by creating a separate movie page with a slider and movies .

**Comment by Kajal-Mishra01** [comment]
Hello @QAZIMAAZARSHAD I am a LGMSOC participant and I really want to work on this project by creating a Separate movie page which is according to age groups preference with a slider.

Please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Hello @QAZIMAAZARSHAD I am a LGMSOC participant and I really want to work on this project by creating a Separate movie page which is according to age groups preference with a slider.
> 
> Please assign this issue to me.

Already assigned to @anushka-srivastava22.
Look for some other issue.

**Comment by Kajal-Mishra01** [comment]
Okay Sir..

**Comment by harshita9621** [comment]
ii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> ii, I would like to work on this issue as LGM SOC'21 participant . Do assign me if possible. Thank You!

Already assigned to @anushka-srivastava22.

**Comment by QAZIMAAZARSHAD** [comment]
@anushka-srivastava22 you can create a PR.

**Comment by anushka-srivastava22** [comment]
Okay Sir.
