### ISSUE TITLE
Change title of the website as displayed in the title bar

### ISSUE THREAD

**Issue by Sourav61** [QAZIMAAZARSHAD/Movie-Streaming-Website#17]
![Capture3](https://user-images.githubusercontent.com/70853906/120574653-5bf89900-c43d-11eb-9a85-90113e016726.JPG)

**Comment by Sourav61** [comment]
I think the title should be ApnaTheatre instead of ApanTheatre.com

**Comment by Sourav61** [comment]
I would like to work on this issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Jagannath8** [comment]
Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue?

@Jagannath8 this is a very basic issue (a cakewalk) I cannot assign more than one participant to this issue.

You can look for any other issue, open new issues, suggest new features, etc.

**Comment by JatanDudeja** [comment]
If this issue is not resolved please assign it to me.
