### ISSUE TITLE
Add Full screen Page Loader animation in beginning

### ISSUE THREAD

**Issue by marizvi** [QAZIMAAZARSHAD/Movie-Streaming-Website#170]
Hi,
I would like to add page load animation, which will appear for very small duration whenever we reload our pages to make our website look more attractive.
Kindly assign me this issue under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
@marizvi this issue is already open #7.

Before opening any issue make sure that no other similar issue is open.
