### ISSUE TITLE
Add Romantic Movie genre in the website

### ISSUE THREAD

**Issue by ish-0709** [QAZIMAAZARSHAD/Movie-Streaming-Website#172]
Hi,
I would like to add a romantic movie genre on the website, romantic movie posters also.
Kindly assign me this issue if there is a need for this genre on the website under LGMSOC

**Comment by QAZIMAAZARSHAD** [comment]
It should be similar to other sections in every respect size, style, effects, etc.

**Comment by ish-0709** [comment]
Yes, sir added the new PR . Please have a look.
