### ISSUE TITLE
Dynamic particles in background

### ISSUE THREAD

**Issue by marizvi** [QAZIMAAZARSHAD/Movie-Streaming-Website#173]
Hi,
I would like to add dynamic particles in background to make our website look more attractive.
Kindly assign me this issue under LGMSOC'21.

**Comment by QAZIMAAZARSHAD** [comment]
Okk. If you want to.

But It can make the website ugly, so if I don't like it I will close this issue without merging your PR.

**Comment by marizvi** [comment]
Yeah sure.
But I won't disappoint you.
