### ISSUE TITLE
Making the Search box to Filter The movies As per the USER

### ISSUE THREAD

**Issue by theSumeetGithub** [QAZIMAAZARSHAD/Movie-Streaming-Website#174]
here i have idea that i can make the search box to back to work as the user search in any movie in website the movie will appear as it......
some thing like these

https://user-images.githubusercontent.com/85386116/121799207-63dbe880-cc48-11eb-824b-efd873fed44b.mp4

**Comment by QAZIMAAZARSHAD** [comment]
@theSumeetGithub this issue is already open #6.

Before opening any issue make sure that no other similar issue is open.
