### ISSUE TITLE
Add scroll to top button 

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#18]
There should be scroll to top in home page 
@QAZIMAAZARSHAD  can i work on this issue under LGM-SOC'21 .

**Comment by kumarishalini6** [comment]
please assign me this issue I'll send PR after 10

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Fine, I will review your PR and merge it.

**Comment by marizvi** [comment]
If this issue is not yet resolved then kindly assign it to me please under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
> If this issue is not yet resolved then kindly assign it to me please under LGMSOC.

Will be resolved soon, PR not merged due to conflicts.
