### ISSUE TITLE
Adding trailer link buttons to the movies and series

### ISSUE THREAD

**Issue by ish-0709** [QAZIMAAZARSHAD/Movie-Streaming-Website#184]
Sir, I want to create a button on all the movie cards so that when that button is clicked directly the trailer of the movie is opened. The button will be in the middle of the movie card just like Netflix.
Kindly assign me this issue under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
Use this issue #54.

Ping me there and I will assign you.
