### ISSUE TITLE
Improve/Redesign home page

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#19]
Can I Redesign the home page . 
@QAZIMAAZARSHAD  please assign this issue to me.

**Comment by kumarishalini6** [comment]
this issue will take time can you please assign me so that i can send PR on 10

**Comment by QAZIMAAZARSHAD** [comment]
> Can I Redesign the home page.
> @QAZIMAAZARSHAD please assign this issue to me.

Yes, go ahead.
But keep in mind, pages of other genres follow the same design and theme as of home page, so do not completely change the style of the home page so it looks completely odd compared to other pages.

**Comment by QAZIMAAZARSHAD** [comment]
> this issue will take time can you please assign me so that I can send PR on 10

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
If you think this issue will take time then you can start working from today but I'll start assigning issues and merging pull requests from 10th June.

**Comment by kumarishalini6** [comment]
Ya sure

**Comment by Ishigupta08** [comment]
@QAZIMAAZARSHAD  whats the theme of this website...

**Comment by coding-geek21** [comment]
Can you assign me , I also wish to contribute to this issue @QAZIMAAZARSHAD

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD  i need to discuss you something

**Comment by QAZIMAAZARSHAD** [comment]
Fine @coding-geek21, I'll review your PR soon.

**Comment by coding-geek21** [comment]
> Fine @coding-geek21, I'll review your PR soon.

Thank you :)
