### ISSUE TITLE
Adding Contact Us Page Button Wherever Required

### ISSUE THREAD

**Issue by JatanDudeja** [QAZIMAAZARSHAD/Movie-Streaming-Website#196]
Please assign me this issue I would like to work on this.

**Changes/Enhancement That Will Done :** 
1. I will add the contact us page button wherever required and and link it.

**Comment by abhshkvrm** [comment]
I also want to work on it !

**Comment by QAZIMAAZARSHAD** [comment]
> I also want to work on it !

Look for any other issue, this is already assigned.

**Comment by JatanDudeja** [comment]
@QAZIMAAZARSHAD this issue has already been solved by someone with out any prior notice so I am closing this issue.
