### ISSUE TITLE
Remove redundant navbar

### ISSUE THREAD

**Issue by Dhanushreddy09** [QAZIMAAZARSHAD/Movie-Streaming-Website#199]
Someone might be working on navbar design for sure but I thought it's worth mentioning that there are two rows of the same navbar items. If it doesn't make any sense, please close this @QAZIMAAZARSHAD . Would like to work on this!

**Comment by QAZIMAAZARSHAD** [comment]
I noticed it just now,

May due to some update.

Resolve this as soon as possible.
Go ahead.
