### ISSUE TITLE
Make website design responsive in mobile phone

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#2]
![WhatsApp Image 2021-06-01 at 6 03 29 PM](https://user-images.githubusercontent.com/56196640/120324053-cc9b9a80-c303-11eb-977b-b4ee0bbf33d9.jpeg)

**Comment by aum-singhal** [comment]
Hello sir. I would like to contribute on this one too 😅
If possible so please assign it to me when LGM-SOC starts
Thanks 😊

and yeah, can i use bootstrap, if needed cause that will make it more responsive and better, a suggestion 😅

**Comment by QAZIMAAZARSHAD** [comment]
Yes, you can use bootstrap.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Kartikey0205** [comment]
@QAZIMAAZARSHAD  hello sir I would like to work on this and wants to modify as much as I can
please assign me this task under the LGM-SOC'21 if possible

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD hello sir I would like to work on this and wants to modify it as much as I can
> please assign me this task under the LGM-SOC'21 if possible

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
But keep in mind, since other contributors are also willing to resolve this issue I will merge only the first PR which will completely resolve this issue.

**Comment by Kartikey0205** [comment]
@QAZIMAAZARSHAD  what about this issue does somebody working on it ? 

If not then would you please assign this to me
and shall I use any framework to make it completely responsive because as I see all Navbar , links and many more are misplaced in other views.

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by nandinimalik16** [comment]
@QAZIMAAZARSHAD  Can you please assign me this issue, I would like to work on it

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Can you please assign me this issue, I would like to work on it

others are already assigned.
Look for any other issues.
