### ISSUE TITLE
Add appropriate font-family to website

### ISSUE THREAD

**Issue by harsh72835** [QAZIMAAZARSHAD/Movie-Streaming-Website#20]

**Comment by sanketcharanpahadi** [comment]
Can I work on this issue @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Naman-Joshi-14** [comment]
sir can i work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
@Naman-Joshi-14 this is an easy issue and other contributors are also willing to solve this issue so I cannot assign you this issue.

Look for any other issues or open new issues.

**Comment by nitishapiplani** [comment]
I will like to work on this if possible assign to me 
Lgm SoC participant

**Comment by QAZIMAAZARSHAD** [comment]
> I will like to work on this if possible assign to me
> LGM SoC participant

@nitishapiplani this is an easy issue and other contributors are also willing to solve this issue so I cannot assign you this issue.

Look for any other issues or open new issues.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey mentors and project admins as the coding period for LGMSOC starts now, could you assign this to me.

@nisha331 this is an easy issue and other contributors are also willing to solve this issue so I cannot assign you this issue.

Look for any other issues or open new issues.

**Comment by QAZIMAAZARSHAD** [comment]
Fine @sanketcharanpahadi I'll review your PR soon.
