### ISSUE TITLE
No colour change on hovering the mouse to kids.html Header

### ISSUE THREAD

**Issue by abhshkvrm** [QAZIMAAZARSHAD/Movie-Streaming-Website#201]
There is no change in colour (red) that we see in other web page on hovering the mouse to 
Home
Movies
Web Series
Kids
TV
Premium
Login
Search
I want to do changes in it and beautify it . may be some other style!

**Comment by QAZIMAAZARSHAD** [comment]
Do it for both kids and web series page.

**Comment by abhshkvrm** [comment]
done for both web series and kids page.

**Comment by QAZIMAAZARSHAD** [comment]
Can you create a hover effect on images of kids and web series page similar to that of other images?

**Comment by abhshkvrm** [comment]
yeah I can add it, will surely do it.

**Comment by abhshkvrm** [comment]
done! now should i make a new branch and commit my changes ?

**Comment by QAZIMAAZARSHAD** [comment]
Sure

**Comment by abhshkvrm** [comment]
remote: Permission to QAZIMAAZARSHAD/Movie-Streaming-Website.git denied to abhshkvrm.
fatal: unable to access 'https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website.git/': The requested URL returned error: 403

how to resolve this error i am getting

**Comment by abhshkvrm** [comment]
have u looked upon the changes @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
@abhshkvrm all the changes you made have been deleted due to an update.

Do you mind opening the same issue again, and making the same changes? For kids and web series page.

**Comment by abhshkvrm** [comment]
ok i will make it !
