### ISSUE TITLE
Add logo in readme

### ISSUE THREAD

**Issue by rishabhrathore055** [QAZIMAAZARSHAD/Movie-Streaming-Website#204]
@QAZIMAAZARSHAD  pls assign  this issues

**Comment by QAZIMAAZARSHAD** [comment]
Describe what updates you want to do,

**Comment by rishabhrathore055** [comment]
@QAZIMAAZARSHAD  want to add this logo
![](https://img.shields.io/badge/Movie_streaming_Website-4285F4?style=for-the-badge&logo=AirPlayVideo&logoColor=white)
And LGN-SOC'21  In Open source Program Section

**Comment by QAZIMAAZARSHAD** [comment]
No don't do that.

Add this logo [Logo](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/UpdatedLogo.png) in the about section of readme.

Change the size of the logo accordingly so it fits with the text.

**Comment by rishabhrathore055** [comment]
![](https://camo.githubusercontent.com/545dec611193714aad0d1051c30defd89b4260dfad79a293c49dc1b841936296/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4d6f7669655f73747265616d696e675f576562736974652d3432383546343f7374796c653d666f722d7468652d6261646765266c6f676f3d416972506c6179566964656f266c6f676f436f6c6f723d7768697465) are you taking about this Logo ?

**Comment by QAZIMAAZARSHAD** [comment]
> No don't do that.
> 
> Add this logo [Logo](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/UpdatedLogo.png) in the about section of readme.
> 
> Change the size of the logo accordingly so it fits with the text.

This logo ->https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/UpdatedLogo.png
