### ISSUE TITLE
Fixed navbar

### ISSUE THREAD

**Issue by Dhanushreddy09** [QAZIMAAZARSHAD/Movie-Streaming-Website#208]
Make navbar fixed so that a user can navigate through to another nav item even if he/she scrolls down to the bottom of the site.

**Comment by sanketcharanpahadi** [comment]
can I work on this issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> can I work on this issue @QAZIMAAZARSHAD

Already assigned to @Dhanushreddy09

**Comment by jatinjain001** [comment]
I would like to work oon it

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work oon it

Already assigned

**Comment by saimanoharhm** [comment]
@Dhanushreddy09 Any update? If you face issue in the code let me know with your problem I am here to help you out.
