### ISSUE TITLE
Image not displaying . 

### ISSUE THREAD

**Issue by MathurUtkarsh** [QAZIMAAZARSHAD/Movie-Streaming-Website#215]
In the top right corner of login page the image is not displaying and  the alternate text for image  is also not displaying  .

**Comment by MathurUtkarsh** [comment]
Please assign me this issue .

**Comment by QAZIMAAZARSHAD** [comment]
@MathurUtkarsh logo is displaying.
![Screenshot (113)](https://user-images.githubusercontent.com/56196640/121853981-35751080-cd0f-11eb-8042-11f25793d4e4.png)
I did not understand what you are talking about.
