### ISSUE TITLE
Cursor should change to the pointer when you hover over cards in movie, kids, webseries and TV page

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Movie-Streaming-Website#227]
The Cursor should change to the pointer when you hover over TV shows in the TV section.
That will make it look like a clickable link.

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue.
Kindly assign me :)

**Comment by QAZIMAAZARSHAD** [comment]
Do it for kids and web series page as well.

**Comment by GaurPeeyush** [comment]
Pull request created.
The cursor now changes to the pointer when you hover above TV shows. 
This issue #227 is fixed with this update.
Kindly review the code and merge the pull request.
Henceforth close this issue :)

**Comment by QAZIMAAZARSHAD** [comment]
> Do it for kids and web series page as well.

You forgot this.

**Comment by GaurPeeyush** [comment]
> > Do it for kids and web series page as well.
> 
> You forgot this.

Oh! okay I'll make the changes

**Comment by GaurPeeyush** [comment]
Flies are updated with reference to this issue #227 
Kindly review the code and merge the pull request :)

**Comment by jatinjain001** [comment]
I want to work on it please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> I want to work on it please assign it to me

Already assigned

**Comment by includestdlibrary** [comment]
@QAZIMAAZARSHAD  is this issue is resolved or can i work on this?

**Comment by QAZIMAAZARSHAD** [comment]
Change cursor to pinter in movies, webseries, kids and tv page.

**Comment by saimanoharhm** [comment]
@jatinjain001 @GaurPeeyush Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Swastik1710** [comment]
Hey!
@QAZIMAAZARSHAD
Can I work on this?

**Comment by Swastik1710** [comment]
Thanks for assigning.
Can you please tell me in brief what all have been done and what needs to be done.

**Comment by QAZIMAAZARSHAD** [comment]
I most of the pages like home and genres the cursor changes to pinter when hover.

But in few pages like movies, kids, webseries it is not changing to pinter when hovering.
Correct it.

**Comment by Swastik1710** [comment]
Do you need it only on cards or should it be there on carousel images also ?

**Comment by QAZIMAAZARSHAD** [comment]
> Do you need it only on cards or should it be there on carousel images also ?

Only on cards.
