### ISSUE TITLE
Update logo in all pages 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#228]
Use this logo -> https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/TheaterLogo.png

Update it in the navbar of every page and in the login/sign-up page.

**Comment by abhijeet141** [comment]
I would like to work on this

**Comment by JatanDudeja** [comment]
Please assign this issue to me.

**Comment by devanshi-code** [comment]
@QAZIMAAZARSHAD can more than one person work on this issue , if yes then plz assign it to me too

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can more than one person work on this issue , if yes then plz assign it to me too

This is a very basic issue, can't assign more than one person.

**Comment by devanshi-code** [comment]
Okay if he can't do that will it be assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> Okay if he can't do that will it be assign it to me

Sure
