### ISSUE TITLE
Add movie slider button

### ISSUE THREAD

**Issue by harshita0802goswami** [QAZIMAAZARSHAD/Movie-Streaming-Website#23]
Adding the slider button to the kids, movie, web-series section and hover effects while clicking over the image

**Comment by QAZIMAAZARSHAD** [comment]
The slider button is a nice idea.
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

But an issue already exists to apply hover effects on images.

**Comment by nandinimalik16** [comment]
@QAZIMAAZARSHAD please assign me this issue. I would like to work on this issue as LGM Soc participant

**Comment by QAZIMAAZARSHAD** [comment]
@harshita0802goswami and @nandinimalik16 a similar issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/56.

Both of you ping me their https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/56 to assign you that issue.
