### ISSUE TITLE
Add facebook, instagram and twitter login page

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Movie-Streaming-Website#232]
Whenever a user clicks on any of logo of facebook , instagram and twitter he/she get redirected to respective page . Suppose a user clicks on insta logo , after click he must reach insta page of movie streaming( if exists) .
![footer](https://user-images.githubusercontent.com/56637948/121954838-d4842180-cd7c-11eb-9358-787dbbca6c16.jpg)

**Comment by JatanDudeja** [comment]
I would like to work on this issue please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue please assign this issue to me.

Already assigned.

**Comment by QAZIMAAZARSHAD** [comment]
> Whenever a user clicks on any of logo of facebook , instagram and twitter he/she get redirected to respective page . Suppose a user clicks on insta logo , after click he must reach insta page of movie streaming( if exists) .
> ![footer](https://user-images.githubusercontent.com/56637948/121954838-d4842180-cd7c-11eb-9358-787dbbca6c16.jpg)

Apply it to all pages.
