### ISSUE TITLE
Premium page enhancement

### ISSUE THREAD

**Issue by AkhilReddy21** [QAZIMAAZARSHAD/Movie-Streaming-Website#234]
I would like to enhance premium page by showing the benefits of premium subscription and I will add the process to the user to get subscription . Just like similar to Netflix subscription page . So , please assign me this issue to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open #26.

Before opening any issue make sure that no other similar issue is open.
