### ISSUE TITLE
Remove the Horizontal scroll 

### ISSUE THREAD

**Issue by Atif0604** [QAZIMAAZARSHAD/Movie-Streaming-Website#24]
I wanna fix the horizontal scroll bug
please assign it to me
I'm a participant of LGM Soc21.
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@Atif0604 a similar issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/1.

Another participant is also willing to resolve that issue and this is an easy issue so I cannot assign this issue to more than one person.
You can look for another issue, or try opening a new issue, suggest new features, etc.

**Comment by Atif0604** [comment]
ohk but if the issue still remains unresolved then please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
Sure
