### ISSUE TITLE
Change footer copyright year using JS

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Movie-Streaming-Website#248]
Hey @QAZIMAAZARSHAD 
I would like to change the footer copyright year using js.
As currently you need to change every time.
I will use js and it will automatically update everytime.
Please assign it to me.
Thanks.

**Comment by QAZIMAAZARSHAD** [comment]
Change it in the footer of every page.

**Comment by Shaishav0507** [comment]
Ok I'll do.

**Comment by jatinjain001** [comment]
I want to work on this please

**Comment by QAZIMAAZARSHAD** [comment]
> I want to work on this please

Already assigned.
