### ISSUE TITLE
In the Premium Page ,there should be one alert box

### ISSUE THREAD

**Issue by aniketartani** [QAZIMAAZARSHAD/Movie-Streaming-Website#25]
On the premium page when we click the click here button, a popup box should appear with showing message like cost of the premium.

**Comment by QAZIMAAZARSHAD** [comment]
@aniketartani this issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/11.

Look for any other issue, or open new issues.

**Comment by QAZIMAAZARSHAD** [comment]
I have created a new issue to design a premium page.

You can work on that issue if interested.
