### ISSUE TITLE
social media icons in footer

### ISSUE THREAD

**Issue by rishika789** [QAZIMAAZARSHAD/Movie-Streaming-Website#251]
The social media icons in footer section on hovering some are becoming red while others are blue . I would like to change those icons.

**Comment by QAZIMAAZARSHAD** [comment]
Red background, black inside.
Apply this color combination on all footer icons, on every page.

**Comment by rishika789** [comment]
okay

**Comment by rishika789** [comment]
sir is the css for footer of every page is in kids.html section ?

**Comment by QAZIMAAZARSHAD** [comment]
> sir is the css for footer of every page is in kids.html section ?

for kids and web series page it is in kids.html and webseries.html.

For others in style.css.

**Comment by rishika789** [comment]
okay sir

**Comment by jatinjain001** [comment]
I would like to work on it

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on it

Already assigned.
