### ISSUE TITLE
Revamp Contact us Page and Navbar

### ISSUE THREAD

**Issue by RahulBansal0502** [QAZIMAAZARSHAD/Movie-Streaming-Website#252]
1. I want to revamp the contact us page.
2.  On hovering navbar links I want that text should be underlined, bold and the color should be bright red instead of faded red.

I want to work on this issues assign it to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead, also look into the responsiveness of the contact page.

**Comment by QAZIMAAZARSHAD** [comment]
If change anything in the navbar then change it for the navbars of all pages.

**Comment by RahulBansal0502** [comment]
ya sure thanks!!

**Comment by QAZIMAAZARSHAD** [comment]
Issue already resolved
