### ISSUE TITLE
Successful alert pop up feature for contact page submit button

### ISSUE THREAD

**Issue by ROHAN842** [QAZIMAAZARSHAD/Movie-Streaming-Website#254]
As when user fills all the detail and clicks on submit button then site takes user 405 not allowed page, I want to add an alert which will pops up and will tell the user that message was delivered successfully with a green tick along with I would also like to add a feature without back end with which user would be sent to a fresh new page on clicking submit button where the message will be written, lets say "Thank you for your submission , Return back ". 

![image](https://user-images.githubusercontent.com/61961107/122104891-c80fcf80-ce35-11eb-8def-7a2d30b5753b.png)

![image](https://user-images.githubusercontent.com/61961107/122104923-d100a100-ce35-11eb-8971-8eff90e56e3f.png)

**Comment by ROHAN842** [comment]
Hey! what's the deadline for completing the task

**Comment by QAZIMAAZARSHAD** [comment]
Take 5 days, if you did not complete I will assign others.

**Comment by ROHAN842** [comment]
Ok
