### ISSUE TITLE
Updating contributing guidelines

### ISSUE THREAD

**Issue by ayushsoni1010** [QAZIMAAZARSHAD/Movie-Streaming-Website#256]
I want to add more guidelines to the contributing.md file

Kindly assign this issue to me :)

Have a look once for reference, what I am going to add to the file

![image](https://user-images.githubusercontent.com/76895975/122110359-11fbb400-ce3c-11eb-9cda-2fcefe76f04c.png)

**Comment by QAZIMAAZARSHAD** [comment]
No need @ayushsoni1010, most points are already present and a few I don't want.
