### ISSUE TITLE
Adding Hover Effect in Navigation Bar

### ISSUE THREAD

**Issue by ishitakapoor26** [QAZIMAAZARSHAD/Movie-Streaming-Website#258]
Adding Hover Effect in Navigation Bar. Also when a page is active there is no hover effect. I also want to add that.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@ishitakapoor26 navigation bar already has hover effect also another issue to improve it is also open #33
