### ISSUE TITLE
Add hover effect in Web Series page

### ISSUE THREAD

**Issue by ishitakapoor26** [QAZIMAAZARSHAD/Movie-Streaming-Website#259]
Add hover effect in Web Series page.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by Sumit11081996** [comment]
@QAZIMAAZARSHAD pls assign me this issue

**Comment by QAZIMAAZARSHAD** [comment]
@ishitakapoor26 and @Sumit11081996 this issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/241.

Before opening any issue make sure that no other similar issue is open.
