### ISSUE TITLE
Design premium page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#26]
Refer to premium pages of some cool websites.
Keep in mind the overall theme of the website.

**Comment by aniketartani** [comment]
OK! I want to work on this. Please assign me

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by rucha0702** [comment]
Could more than one person  be working on the same issue? I am new to open source, so I thought I should ask first.

**Comment by Aiswarika** [comment]
Can I work on this issue? @QAZIMAAZARSHAD

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD  I just have a doubt does this project involve back-end like login and sign-up using mysql and php?

**Comment by Naman-Joshi-14** [comment]
Can i work on this project? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@Aiswarika and @Naman-Joshi-14 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by aniketartani** [comment]
After completing this, will we get any certificate?

**Comment by Naman-Joshi-14** [comment]
Thank you so much for giving me this opportunity.

**Comment by Ishigupta08** [comment]
QAZIMAAZARSHAD i also want to work on this issue...can we design by ourself or uh will provide a layout

**Comment by Ishigupta08** [comment]
@QAZIMAAZARSHAD  i also want to worked on this issue...do we need to make this page by ourself or any specific layout by you

**Comment by Ishigupta08** [comment]
And i want to know these issues are clashed by many people...so can it be assigned to more than one person

**Comment by Rishita11** [comment]
I would like to work on this. Please assign me this @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I also want to work on this issue...do we need to make this page by ourselves or any specific layout by you

Implement your own ideas. Just keep in mind the color, theme, and style of this website.

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 and @Ishigupta08 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by Ishigupta08** [comment]
@QAZIMAAZARSHAD how will everyone solve this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD how will everyone solve this issue?

Refer to premium pages of some cool websites.
Keep in mind the overall theme of the website.
Among all the contributors whose design will be best, their PR will be merged.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
It has been 17days and 7 people are working on this, still, this issue is unresolved.


If anyone is not working then unassign yourself.

**Comment by ishitakapoor26** [comment]
> It has been 17days and 7 people are working on this, still, this issue is unresolved.
> 
> If anyone is not working then unassign yourself.

@QAZIMAAZARSHAD Sorry for delay because I had my end sem exams last week. I am working on it and will shortly create a pr.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls review pr.

**Comment by QAZIMAAZARSHAD** [comment]
Will review soon.
