### ISSUE TITLE
Add membership page

### ISSUE THREAD

**Issue by ishitakapoor26** [QAZIMAAZARSHAD/Movie-Streaming-Website#263]
I will add a membership page listing yearly and monthly subscription price and offers.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@ishitakapoor26 this issue is already open #26.

Don't open similar issues again and again first verify.
