### ISSUE TITLE
**Adding a scroll to top button**

### ISSUE THREAD

**Issue by mdinesh124** [QAZIMAAZARSHAD/Movie-Streaming-Website#266]
Adding a scroll to top button makes it easy to scroll from bottom to top on just clicking a button.

**Comment by mdinesh124** [comment]
@QAZIMAAZARSHAD Please assign me this under LGMSOC

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open #18.

Before opening any issue make sure that no other similar issue is open.

**Comment by mdinesh124** [comment]
@QAZIMAAZARSHAD I will definitely check from next time whether same issue is present or not. 
Can you assign me #18 issue. I can work on that.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I will definitely check from next time whether same issue is present or not.
> Can you assign me #18 issue. I can work on that.

That issue will be resolved soon, can't assign you

**Comment by mdinesh124** [comment]
Ok
