### ISSUE TITLE
Remove the "Have a look on various movies" drop down and add drop down list of all genres in navbar

### ISSUE THREAD

**Issue by rishika789** [QAZIMAAZARSHAD/Movie-Streaming-Website#267]
![Screenshot (894)](https://user-images.githubusercontent.com/78673968/122184464-dbf51900-cea9-11eb-80ad-8c2cebabbeaf.png)

**Comment by QAZIMAAZARSHAD** [comment]
No, don't add it to the center.

Redesign it completely, also it is very deep two dropdowns are present improve that also.
Rename varieties to 'genres'.


Also take care of responsiveness.

**Comment by rishika789** [comment]
okay. where is the varieties word but ?

**Comment by QAZIMAAZARSHAD** [comment]
Click on have a look at various movies.

**Comment by rishika789** [comment]
okay

**Comment by saimanoharhm** [comment]
@rishika789 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by wc0801** [comment]
Hi can I contribute in this?
