### ISSUE TITLE
Adding FAQ section to homepage.

### ISSUE THREAD

**Issue by ishitakapoor26** [QAZIMAAZARSHAD/Movie-Streaming-Website#268]
FAQ markup is present in login page but it holds no content and redirects to login page. I want to add FAQ section to homepage and when we click on FAQ in login page we will be redirrected to homepage FAQ section.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
No don't add it to the home page, create a separate FAQ page, and link it to all the footers of every page.

**Comment by Sumit11081996** [comment]
@QAZIMAAZARSHAD  can you assign me this issue

**Comment by harshita9621** [comment]
ii, I would like to work on this issue as LGM SOC'21 participant. Do assign me if possible. Thank You!

**Comment by ishitakapoor26** [comment]
Hey @Sumit11081996 @harshita9621 I'm already working on it. Pls look for some other issue.

**Comment by harshita9621** [comment]
Can I work on this issue @QAZIMAAZARSHAD

**Comment by ishitakapoor26** [comment]
@harshita9621 I'm already working on this issue, pls look for some other issue. Good Luck!

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue @QAZIMAAZARSHAD

@harshita9621 I have assigned you another issue, you can start working on that.
