### ISSUE TITLE
Improving splash screen

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#281]

**Comment by QAZIMAAZARSHAD** [comment]
Now it is fine.

I think GitHub takes a lot of time to load.


But still, you can improve, try some other effect, Logo should appear clearly for at least 3-5 seconds.
And use better color for effects, brown doesn't look good.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
https://user-images.githubusercontent.com/69043944/122321563-83854200-ced0-11eb-8754-d8bc1d7b2b0a.mp4

**Comment by QAZIMAAZARSHAD** [comment]
No, I want more focus on the logo.

Make logo large, and also apply effects on the image itself.

**Comment by QAZIMAAZARSHAD** [comment]
Also, their is a bug in the splash screen, it appears every time user goes to the home screen, It should appear only for the first time when the website opens.

**Comment by saimanoharhm** [comment]
@kumarishalini6 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 Any update? If you face issue in the code let me know with your problem I am here to help you out.

So sorry I forgot to inform you that I am little bit busy because of exam 
So sorry can you please give me some more time?

**Comment by QAZIMAAZARSHAD** [comment]
Fine
