### ISSUE TITLE
Redirect user to home page after clicking 'return' on form submitted popup in contactus.html page

### ISSUE THREAD

**Issue by ROHAN842** [QAZIMAAZARSHAD/Movie-Streaming-Website#288]
As when user fills all the detail and clicks on submit button then site takes user 405 not allowed page, I want to add an alert which will pops up and will tell the user that message was delivered successfully, thanks for their submission. 

Can I work on this issue.

**Comment by ROHAN842** [comment]
Hey @QAZIMAAZARSHAD  actually I have removed that feature of that user will be directed to a fresh new on submission as that was not safe now the new feature is as when user clicks on submit button a box will popup on the same page and a message will be delivered as "Message was delivered successfully!! Thanks for your submission" and also it will consists of an OK button as soon as user will click on that OK button that alert popup box will be closed and user will remain stayed on the same contact page.

**Comment by QAZIMAAZARSHAD** [comment]
Ok fine.

Try to beautify alert with css, use red and black colors.
