### ISSUE TITLE
Make button responsive in dummy.html

### ISSUE THREAD

**Issue by WebShivam** [QAZIMAAZARSHAD/Movie-Streaming-Website#293]
The button that is on Premium Page of the website can be redesigned with responsiveness in mind, The redesigning of the button with its proper size will enhance its look on the page. Here is the link of the page I'm taking about `https://qazimaazarshad.github.io/Movie-Streaming-Website/dummy.html` 

I've also provided  the picture of the button for further reference

![button-img](https://user-images.githubusercontent.com/64413107/122417853-6b342680-cfa7-11eb-8ee6-5e42bb6dc992.jpg)

**Comment by mehulmb1** [comment]
@QAZIMAAZARSHAD Please assign this to me i know how to make it responsive

**Comment by WebShivam** [comment]
Hi @QAZIMAAZARSHAD I did this
I just forgot to push the changes
I'm doing it now
