### ISSUE TITLE
Need to Work on Movies Page

### ISSUE THREAD

**Issue by WebShivam** [QAZIMAAZARSHAD/Movie-Streaming-Website#294]
The design of movie page doesn't looks cool, Maybe there's a problem with linking CSS file You can look at it here : 

![Screenshot_40](https://user-images.githubusercontent.com/64413107/122419551-9e2aea00-cfa8-11eb-8200-da6cfcf40a09.jpg)

Here is the link of the following page  `https://qazimaazarshad.github.io/Movie-Streaming-Website/movies.html`

**Comment by QAZIMAAZARSHAD** [comment]
Yaa someone was working on this but she made the changes without updating the repo and messed it up.

Completely update this page like the other pages.

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me this issue.

If the issue remains unresolved for a few more days then I will assign you.

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGMSOC'21
