### ISSUE TITLE
Login and Signup page needs to be Mobile Friendly

### ISSUE THREAD

**Issue by WebShivam** [QAZIMAAZARSHAD/Movie-Streaming-Website#295]
Both Login page, as well as SignUp page, needs to be designed responsively
this is how they look like at Mobile view currently 👇 

## LogIn Page
![login-page(Moto G4)](https://user-images.githubusercontent.com/64413107/122422884-21e5d600-cfab-11eb-8580-623719271787.png)

## SignUp Page

![Sign-Up page (Moto G4)](https://user-images.githubusercontent.com/64413107/122422903-25795d00-cfab-11eb-885a-d946b111206d.png)

**Comment by shivshankar9** [comment]
could you please assign to me so i can fix

**Comment by QAZIMAAZARSHAD** [comment]
> could you please assign to me so i can fix

Already assigned, if it remains unresolved for a few days then I will assign you.

**Comment by Godwindaniel10** [comment]
@QAZIMAAZARSHAD Can i work on this issue?
