### ISSUE TITLE
Suggestion regarding Movies Poster

### ISSUE THREAD

**Issue by WebShivam** [QAZIMAAZARSHAD/Movie-Streaming-Website#296]
In my opinion all the Movies Poster can be designed like cards (similar to Posters that are designed on `Kids` Page). This will enhance the site and will provide the premium look to page as Movies Poster doesn't have same design all over the site

This is how Poster card looks like on Kids page 👇 

![movie-poster-card](https://user-images.githubusercontent.com/64413107/122425863-6d00e880-cfad-11eb-8c5a-a68d8d226aeb.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
But cards on the kids and webseries page don't have a hover effect.

Try to apply the same hover effect on kids and webseries page as well.

**Comment by QAZIMAAZARSHAD** [comment]
The website has been updated.

Now, make movie cards of kids and web series pages similar to that of other pages in every respect.

**Comment by saimanoharhm** [comment]
@WebShivam Any update? If you face issue in the code let me know with your problem I am here to help you out.
