### ISSUE TITLE
Change color of social media icons in footer

### ISSUE THREAD

**Issue by rishika789** [QAZIMAAZARSHAD/Movie-Streaming-Website#297]
the footer icons are blue not matching with the colour theme of website. I would like to change it to red.

![Screenshot (912)](https://user-images.githubusercontent.com/78673968/122442385-25358d80-cfbc-11eb-8079-6c3ff6d435b2.png)

**Comment by rishika789** [comment]
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Okk, but then change the color of the hover effect as well, because hover color is red and black, it will not be distinguishable.

**Comment by rishika789** [comment]
> Okk, but then change the color of the hover effect as well, because hover color is red and black, it will not be distinguishable.

no actually on hovering icons become black and background is red so it will be distinguised.
As i will make icons red and on hovering it will change to black.

**Comment by wastech** [comment]
is this issue still available?

**Comment by rishika789** [comment]
> is this issue still available?

i m working on this

**Comment by QAZIMAAZARSHAD** [comment]
> is this issue still available?

Already assigned.

**Comment by wastech** [comment]
Alright
