### ISSUE TITLE
Apply creative hover effect on all images

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#3]

**Comment by iam-sakshi** [comment]
can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by rucha0702** [comment]
Can I also try this?

**Comment by QAZIMAAZARSHAD** [comment]
Sure, go ahead.

**Comment by rucha0702** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/77936051/120881294-a751a980-c5ed-11eb-9bd7-6b1bec390b24.png)
![Screenshot (13)](https://user-images.githubusercontent.com/77936051/120881306-b2a4d500-c5ed-11eb-97a2-64cdc5aefac1.png)

**Comment by rucha0702** [comment]
Is this okay? I have added opacity.

**Comment by QAZIMAAZARSHAD** [comment]
@rucha0702 this doesn't look too well, I suggest you to try some other style.

**Comment by rucha0702** [comment]
@QAZIMAAZARSHAD okay, I will try something else.

**Comment by SamikshaSankar** [comment]
Please assign this issue to me ...I will use flip box for this

**Comment by QAZIMAAZARSHAD** [comment]
@SamikshaSankar go ahead,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by utkarshgoel10** [comment]
@QAZIMAAZARSHAD Can you please assign me this issue, I'm having an idea of a zoom effect that will look great on these.

**Comment by QAZIMAAZARSHAD** [comment]
@iam-sakshi I will review your PR soon.

**Comment by coding-geek21** [comment]
I want to improve the design of the cards can you please assign me too @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@iam-sakshi your design was better but It had many irregularities as well.
It was occupying too much space.
Huge space between the bottom card and the footer.
On flipping card text was not at the center.


You can fix these bugs and again open the issue to improve the image hover effect.

And others also who are working on this issue if they believe their design is an improvement they can open new issue.
