### ISSUE TITLE
Design web series page

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#30]
I would like to work on this issue @QAZIMAAZARSHAD can you please assign me under LGM-SOC

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD  I just have a doubt does this project involve back-end like login and sign-up using mysql and php?

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue @QAZIMAAZARSHAD can you please assign me under LGM-SOC

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I just have a doubt does this project involve back-ends like login and sign-up using MySQL and PHP?

No, but you are always welcome to improve this website.

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD 
Can i implement same design as done in Kids page issue #35 for this page also?

**Comment by QAZIMAAZARSHAD** [comment]
Sure,

**Comment by coding-geek21** [comment]
Thank you :) I will make PR tomorrow
