### ISSUE TITLE
Movies page

### ISSUE THREAD

**Issue by RiyaGupta89** [QAZIMAAZARSHAD/Movie-Streaming-Website#302]
![4](https://user-images.githubusercontent.com/72425181/122543071-029d8600-d049-11eb-8c9e-4eeadd5b723c.png)
When a user clicks on movies to come to movies page, it somewhat looks like this which don't look nice. I can make the page look good and remove all the extra padding and stuff.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 this issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/294.
