### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by RiyaGupta89** [QAZIMAAZARSHAD/Movie-Streaming-Website#303]
![5](https://user-images.githubusercontent.com/72425181/122543531-80fa2800-d049-11eb-893f-64900e6599f1.png)
The sign in button comes out of the container, I can resolve this issue.

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/295.
