### ISSUE TITLE
Replace wrong movie cards on all pages

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Movie-Streaming-Website#307]
The movie Gangs of Wasseypur has the poster of its second part, Movie is the first part, so its poster needs to be replaced with the first part one.

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue, kindly assign!

**Comment by QAZIMAAZARSHAD** [comment]
Also, Gangs of waseeypur poster is present in the web series section as well so replace it with some other webseries.

**Comment by QAZIMAAZARSHAD** [comment]
@GaurPeeyush also replace movie cards in TV section.

Replace them with the same size cards as other pages.

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGM SOC 21
