### ISSUE TITLE
the signin button in the login page is overflowing.

### ISSUE THREAD

**Issue by jugeshraghav** [QAZIMAAZARSHAD/Movie-Streaming-Website#308]
![Screenshot (108)](https://user-images.githubusercontent.com/74092377/122599956-bd9b4300-d08c-11eb-8af8-a78091515c57.png)

**Comment by jugeshraghav** [comment]
i would like to work on the issue.

**Comment by jugeshraghav** [comment]
the sign up page button is also overflowing.
@QAZIMAAZARSHAD if you guide me and let me know the type of signin and signup page you want.
I f any modifications need to be done or just have to set the button size.

**Comment by QAZIMAAZARSHAD** [comment]
No page is fine.

Just resolve the button issue on both pages.

**Comment by jugeshraghav** [comment]
Sure.
