### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#31]
I would like to work on this issue under LGM-SOC , Can you please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 this issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/9.

You can look for any other issues or open new issues.
