### ISSUE TITLE
footer is not consistent in all the pages. 

### ISSUE THREAD

**Issue by jugeshraghav** [QAZIMAAZARSHAD/Movie-Streaming-Website#311]
please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@jugeshraghav which pages you are talking about?

**Comment by jugeshraghav** [comment]
In some pages the font size is same and in other pages it is different. And
while navigating through the website the inconsistent behaviour is not
looking good.

**Comment by QAZIMAAZARSHAD** [comment]
Okk go ahead.

Also the footer in mobile view is very large, do something about that also.

**Comment by jugeshraghav** [comment]
Sure

**Comment by nitishapiplani** [comment]
may i work on it

**Comment by QAZIMAAZARSHAD** [comment]
> may i work on it

This one is already assigned.

You are already assigned to many issues complete them first then look for other issues.

**Comment by nitishapiplani** [comment]
> > may i work on it
> 
> This one is already assigned.
> 
> You are already assigned to many issues complete them first then look for other issues.

okk sir
