### ISSUE TITLE
the movies page should be improvised as it is completely broken.

### ISSUE THREAD

**Issue by jugeshraghav** [QAZIMAAZARSHAD/Movie-Streaming-Website#312]
![Screenshot (110)](https://user-images.githubusercontent.com/74092377/122605596-4a49ff00-d095-11eb-87b2-40b5fb2920ac.png)
![Screenshot (109)](https://user-images.githubusercontent.com/74092377/122605610-503fe000-d095-11eb-96d2-2ec93c5d6ac0.png)

**Comment by jugeshraghav** [comment]
please assign this issue to me .

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open #294.
