### ISSUE TITLE
I would like to add score card of LGMSOC in read me

### ISSUE THREAD

**Issue by nisha331** [QAZIMAAZARSHAD/Movie-Streaming-Website#314]
![1](https://user-images.githubusercontent.com/76838660/122633149-9e380080-d0f4-11eb-9d28-8ba6c735950a.PNG)
I as a LGMSOC participants would like to work on it.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

Add it just beside the Let's Grow More logo.
