### ISSUE TITLE
changing the position of the  Input-sign in button 

### ISSUE THREAD

**Issue by dhruv-varshney** [QAZIMAAZARSHAD/Movie-Streaming-Website#318]
![Selection_041](https://user-images.githubusercontent.com/53403223/122637941-dea47800-d10e-11eb-9b02-231310b404aa.png)

as you can see the sign-in button is not placed properly I want to correct the alignment of the sign-in button. please assign me this issue

**Comment by QAZIMAAZARSHAD** [comment]
@dhruv-varshney this issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/308.

Before opening any issue make sure that no other similar issue is open.

**Comment by dhruv-varshney** [comment]
ok
