### ISSUE TITLE
Add custom scrollbar

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#32]
I would like to work on this issue under LGM-SOC , Can you please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by coding-geek21** [comment]
![image](https://user-images.githubusercontent.com/53329034/121005282-4a9ced00-c7ad-11eb-9093-e9c217e51ded.png)

@QAZIMAAZARSHAD  I'm done with custom scrollbar, do check it kindly and  suggest your views and changes , Thank you :)

**Comment by QAZIMAAZARSHAD** [comment]
Fine,

Just match the red color of the scroll bar with the color used in the website.

**Comment by coding-geek21** [comment]
Sure , I will make changes

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD Just a suggestion shall we replace the slider with carousel it will make the website look even more attractive

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Just a suggestion shall we replace the slider with a carousel it will make the website look even more attractive

Okk, if you want to.

 I'll assign you the issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/8, just ping me over there.

**Comment by coding-geek21** [comment]
> > @QAZIMAAZARSHAD Just a suggestion shall we replace the slider with a carousel it will make the website look even more attractive
> 
> Okk, if you want to.
> 
> I'll assign you the issue number #8, just ping me over there.

Yes it would be a pleasure for me to work on it , Thank you :) @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 I'll review your PR sson.
