### ISSUE TITLE
Change hover effect on social icons and scroll button in footer

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#321]
For social icons, contact, and scroll to top button color :

Without Hover - Background Red, Inside black

On Hover - Background white, inside red

**Comment by shivshankar9** [comment]
I would like to give a try on this issue
Can you assign me so I can Start Working.

**Comment by YonaMiti** [comment]
Can i try it please

**Comment by QAZIMAAZARSHAD** [comment]
> Can i try it please

Already assigned.

**Comment by shivshankar9** [comment]
> For social icons, contact, and scroll to top button color :
> 
> Without Hover - Background Red, Inside black
> 
> On Hover - Background white, inside red
can you checkout this hover is ok!!
![Screenshot (187)](https://user-images.githubusercontent.com/69760883/122661312-92a51200-d1a6-11eb-8074-377b5476d580.png)

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 Follow this.

For social icons, contact, and scroll to top button color :

Without Hover - Background Red, Inside black

On Hover - Background white, inside red

**Comment by shivshankar9** [comment]
i don't understand which background and which one inside,
are u saying about icon or footer,
if you could help me in that so i can get clear idea,
check twitter button on hover 
same like that or different
and without hover see others icons

**Comment by QAZIMAAZARSHAD** [comment]
> > For social icons, contact, and scroll to top button color :
> > Without Hover - Background Red, Inside black
> > On Hover - Background white, inside red
> > can you checkout this hover is ok!!
> > ![Screenshot (187)](https://user-images.githubusercontent.com/69760883/122661312-92a51200-d1a6-11eb-8074-377b5476d580.png)

In this image without hover color of linkedin, insta, github, playstore and app store is fine.

And on hover color of twitter is fine.



Make all social icons, scroll button and contact button similar.
