### ISSUE TITLE
Title, description, and buttons inside movie cards not aligned properly

### ISSUE THREAD

**Issue by rushikadivar** [QAZIMAAZARSHAD/Movie-Streaming-Website#323]
name of the interstellar card  while flip
card flip time duration button size 
the layout of the all card in fantasy file can be 3 to 4 per raw with certain padding

**Comment by rushikadivar** [comment]
can I go for it?

**Comment by QAZIMAAZARSHAD** [comment]
Whenever you open any issue try to be clear, I was not able to understand anything from what you wrote in the title and description until I opened the fantasy page.

**Comment by QAZIMAAZARSHAD** [comment]
> can I go for it?

Yaa sure,

But other than the fantasy page, review every single card of every page and do the modification if needed.

**Comment by rushikadivar** [comment]
I'll keep in mind these things

**Comment by saimanoharhm** [comment]
@rushikadivar Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by priyansh11786** [comment]
Can I go for this issue if no one has been assigned?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I go for this issue if no one has been assigned?

Under DCP or LGMSoC?

**Comment by priyansh11786** [comment]
DCP!

**Comment by priyansh11786** [comment]
> > Can I go for this issue if no one has been assigned?
> 
> Under DCP or LGMSoC?

DCP!
