### ISSUE TITLE
Few movie cards redirecting to trailer of another movie

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#324]
For a few movie cards on clicking the trailer button in the movie card description, the trailer of another movie is opening correct it.
Example - Aashram series ( in war & politics)

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by mehulmb1** [comment]
@QAZIMAAZARSHAD  Please assign this to me I can do this easily.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD you want to say that trailers are redirected to other seasons like two or other and not one right?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD you want to say that trailers are redirected to other seasons like two or other and not one right?
> Because I have checked there are only two of them which are redirecting to different trailers.

When I have checked there were many such cards, way more than 2.

Don't care about the season, all the movie card should redirect to their own trailer.

**Comment by ishitakapoor26** [comment]
> > @QAZIMAAZARSHAD you want to say that trailers are redirected to other seasons like two or other and not one right?
> > Because I have checked there are only two of them which are redirecting to different trailers.
> 
> When I have checked there were many such cards, way more than 2.
> 
> Don't care about the season, all the movie card should redirect to their own trailer.

okay I'll check again.

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGMSOC 21
