### ISSUE TITLE
footer text size are too big, the scroller effect nedds to be changed and static file should be seprate 

### ISSUE THREAD

**Issue by rushikadivar** [QAZIMAAZARSHAD/Movie-Streaming-Website#328]
The font size of the footer is too big
scroller (at the end) position relative needs to be fixed and after some scrolling it should be visible
and it also taking a time to return back to top

the static portion should be a separate file  for well maintaining

**Comment by QAZIMAAZARSHAD** [comment]
@rushikadivar these issues are already open #320 and #311.
And for CSS part, yes the entire code has become hard to understand but many participants are working on this project so this is not the right time to change entire code style.
Will open this issue again later.
