### ISSUE TITLE
Improve navbar design

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#33]

**Comment by QAZIMAAZARSHAD** [comment]
Can you tell me your ideas, how you plan to improve the navbar?

**Comment by kumarishalini6** [comment]
Sure

**Comment by kumarishalini6** [comment]
We have 2 navbar 
1st one (which is at the top )- first I will make it fixed , add the logo in the navbar ,  the navbar items at the right hand side and the search box at the center , adding some style and hover effects.
2nd navbar- I was thinking to make it as side navbar, and the menu bar at the right hand side of the logo  with same style . Why side navbar because there is lots of things in this navbar and if someone wants to add something that will make that odd .

**Comment by kumarishalini6** [comment]
One of things I want to ask can I change the background colour??

**Comment by prakhargupta1632000** [comment]
I would like to improve navbar @QAZIMAAZARSHAD can you  please assign it to me under LGM-SOC.

**Comment by prakhargupta1632000** [comment]
First I will add logo properly in navbar . and make search button more attractive using bootstrap. In short I will make complete navbar more attractive and responsive using bootstrap. Also make navbar stick at top so that it will be visible when we scroll down. Also add some more attractive fonts to navbar. Also add second navbar in first navbar using a dropdown button in first navbar.

**Comment by QAZIMAAZARSHAD** [comment]
Ok, go-ahead.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

The best design will be accepted.

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by kumarishalini6** [comment]
@V-Yeshwanth  I am requesting you to please create new issue because I am also a participant and it is tough to find issue for me too please 🙏🙏.

**Comment by QAZIMAAZARSHAD** [comment]
Yes, @kumarishalini6 you guys are willing to work on every single issue. Remember you won't get any points for being assigned to an issue, you have to solve these issues. 
If you are assigned to 10 issues then you cannot work on every single issue simultaneously, in that case, I will not wait for you to complete your work if I receive any PR prior to yours's which solves that issue then I will merge it and close the issue. 

So focus on only a single issue, once you complete it then go for other issues.

**Comment by JatanDudeja** [comment]
I would like to work on this issue.

***Changes I would make :-***
1. I will add the logo to the left most side of the top most navbar.
2. I will center the nav bar items .
3. I will change the color of the navbar according to the contrast of the website.

**Comment by QAZIMAAZARSHAD** [comment]
Remember only the best design/solution will be accepted.

**Comment by nitishapiplani** [comment]
i would like to work on this iff possible 
lgm soc participant

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on this iff possible
> lgm soc participant

Remember only the best design/solution will be accepted.

**Comment by nitishapiplani** [comment]
> > i would like to work on this iff possible
> > lgm soc participant
> 
> Remember only the best design/solution will be accepted.

okkay sure

**Comment by JatanDudeja** [comment]
Hey I have design attached below for the top nav bar please have look. if it fits your project do comment.


Video -  https://user-images.githubusercontent.com/81140308/121788303-e2556d80-cbe9-11eb-8f08-115d0f8a2f15.mov



Image When Search Box Is Not Hovered -      <img width="1440" alt="Nav Bar Without Hover On Search Bar" src="https://user-images.githubusercontent.com/81140308/121788357-3eb88d00-cbea-11eb-803c-29b7a2885306.png">




Image When Search Button Is Hovered -    <img width="1440" alt="Nav Bar With Hover On Search Bar" src="https://user-images.githubusercontent.com/81140308/121788339-25174580-cbea-11eb-809b-13052c48c0f1.png">

**Comment by QAZIMAAZARSHAD** [comment]
> Hey I have design attached below for the top nav bar please have look. if it fits your project do comment.
> 
> Video - https://user-images.githubusercontent.com/81140308/121788303-e2556d80-cbe9-11eb-8f08-115d0f8a2f15.mov
> 
> Image When Search Box Is Not Hovered - <img alt="Nav Bar Without Hover On Search Bar" width="1440" src="https://user-images.githubusercontent.com/81140308/121788357-3eb88d00-cbea-11eb-803c-29b7a2885306.png">
> 
> Image When Search Button Is Hovered - <img alt="Nav Bar With Hover On Search Bar" width="1440" src="https://user-images.githubusercontent.com/81140308/121788339-25174580-cbea-11eb-809b-13052c48c0f1.png">

Fine.

Apply this navbar in every single page, except login and signup page.
And replace logo with this https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/UpdatedLogo.png

**Comment by QAZIMAAZARSHAD** [comment]
Anyone still working on this, or shall I close this?

**Comment by nitishapiplani** [comment]
ya i am
