### ISSUE TITLE
Update screenshot section in Readme

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#332]

**Comment by shivshankar9** [comment]
all pages screenshot i have to add right!!!

**Comment by QAZIMAAZARSHAD** [comment]
> all pages screenshot i have to add right!!!

Not all.

home page, contact, sign up, kids, show search functionality, flip effect trailer.

Make gif to show working.

**Comment by QAZIMAAZARSHAD** [comment]
Make screenshots like this readme https://github.com/smaranjitghose/doc2pen
