### ISSUE TITLE
Improving the UI of navigation bar for mobile view

### ISSUE THREAD

**Issue by JahnaviKashyap19** [QAZIMAAZARSHAD/Movie-Streaming-Website#335]
Adding hover to the navigation bar of the website in mobile view and changing the color of the hamburger icon as the background of the website is dark. Also adding hover to the hamburger icon. Raising this issue under LGM Soc'21.

**Comment by nitishapiplani** [comment]
may i work on this

**Comment by QAZIMAAZARSHAD** [comment]
> may i work on this

No, already assigned.

**Comment by nitishapiplani** [comment]
> > may i work on this
> 
> No, already assigned.

okk

**Comment by JahnaviKashyap19** [comment]
@QAZIMAAZARSHAD I have made the pull request. Please review it.

**Comment by QAZIMAAZARSHAD** [comment]
@JahnaviKashyap19 it is fine in mobile view but you have ruined the desktop view.

![image](https://user-images.githubusercontent.com/56196640/122886197-5c5dc300-d35d-11eb-9fab-2d192c5fd4a5.png)


Change the desktop view navbar back to normal.
Also, for the mobile view you have not done the changes in action, comedy, horror, etc. other pages do changes in them also.

Also, the hover effect is faded red, change it to red color similar to the website.

**Comment by JahnaviKashyap19** [comment]
Should I remove the icons from the navigation bar?

**Comment by QAZIMAAZARSHAD** [comment]
> Should I remove the icons from the navigation bar?

In mobile view they were fine.

Remove them from desktop view.
