### ISSUE TITLE
Changing the design of the movies page

### ISSUE THREAD

**Issue by JahnaviKashyap19** [QAZIMAAZARSHAD/Movie-Streaming-Website#343]
Changing the design of the movies page and making it similar to the rest of the pages.
The CSS of the movies page needs work as it looks very different from the rest of the pages. Please assign me this issue under LGMSoc'21. Thank you.

**Comment by harshita9621** [comment]
can I work on this issue?

**Comment by JahnaviKashyap19** [comment]
> can I work on this issue?

@harshita9621 I have already opened the issue . You can open another issue.

**Comment by QAZIMAAZARSHAD** [comment]
@JahnaviKashyap19 and @harshita9621 this issue is already open.

Before opening any issue make sure that no other similar issue is open,

**Comment by QAZIMAAZARSHAD** [comment]
Ping me on https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/294 and ask to assign you.
