### ISSUE TITLE
Not redirecting to quiz.html after successful sign up

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#347]

**Comment by jugeshraghav** [comment]
i would like to work on the issue.

**Comment by saimanoharhm** [comment]
@jugeshraghav Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by dilroseR** [comment]
i would like to work on this

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this

Under DCP or LGMSoC?

**Comment by dilroseR** [comment]
> > I would like to work on this
> 
> Under DCP or LGMSoC?

dcp
