### ISSUE TITLE
Align the register button properly in sign up page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#348]
![Screenshot (150)](https://user-images.githubusercontent.com/56196640/122893710-338cfc00-d364-11eb-9ab8-2be342de8a8f.png)

**Comment by jugeshraghav** [comment]
i would like to work on the issue.

**Comment by bansiparsania** [comment]
Please assign this to me

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on the issue.

@jugeshraghav I have assigned you another issue.
Let's give this opportunity to @bansiparsania.

**Comment by jugeshraghav** [comment]
Ya sure 😇

**Comment by bansiparsania** [comment]
Thank you 👍🏻

**Comment by bansiparsania** [comment]
Can I align register button in center ?

**Comment by QAZIMAAZARSHAD** [comment]
Like this 

![image](https://user-images.githubusercontent.com/56196640/122904495-07767880-d36e-11eb-9468-f6a284fd7302.png)

**Comment by 889-dj** [comment]
heyyy! i would love to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> heyyy! i would love to work on this issue

Already assigned. Look for some other issues.

**Comment by 889-dj** [comment]
sure thanks....

**Comment by bansiparsania** [comment]
plz checkout my changes
