### ISSUE TITLE
Design kids page

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#35]
I would like to work on this issue @QAZIMAAZARSHAD , please assign me

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Rishita11** [comment]
I would like to work on this. Please Assign this to me. @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by coding-geek21** [comment]
Hi @QAZIMAAZARSHAD  I have designed the kids page , can you please give your feedback on it .
I will change the pictures, for now i just used some random pictures , and if you think any changes has to be done please inform me, I would be happy to do :)

https://screenrec.com/share/RFlcYVyCQA

**Comment by QAZIMAAZARSHAD** [comment]
> Hi @QAZIMAAZARSHAD I have designed the kids page, can you please give your feedback on it.
> I will change the pictures, for now, I just used some random pictures, and if you think any changes have to be done please inform me, I would be happy to do :)
> 
> https://screenrec.com/share/RFlcYVyCQA

It's fine.

Good Job. Make the changes and make PR.

**Comment by coding-geek21** [comment]
> > Hi @QAZIMAAZARSHAD I have designed the kids page, can you please give your feedback on it.
> > I will change the pictures, for now, I just used some random pictures, and if you think any changes have to be done please inform me, I would be happy to do :)
> > https://screenrec.com/share/RFlcYVyCQA
> 
> It's fine.
> 
> Good Job. Make the changes and make PR.

sure , Thank you
