### ISSUE TITLE
Check responsiveness of all the pages in mobile view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#357]

**Comment by shivshankar9** [comment]
Assign me

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGMSOC 21

**Comment by saimanoharhm** [comment]
@kshitija-2001 @shivshankar9 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Aas7ha** [comment]
Please assign me this issue under LGMSOC 21

**Comment by QAZIMAAZARSHAD** [comment]
@Aas7ha any updates?

**Comment by Swastik1710** [comment]
Hey, I would like to try this out.
Please assign it to me.
