### ISSUE TITLE
Link all the pages with each other

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#358]
Also, check all the hyperlinks and buttons in the footer and navbar.

On clicking the logo, it should redirect to home.html. Many logos in the footer and navbar are redirecting to the index page.
All pages are redirecting to dummy.html instead of premium.html.

Test the entire website and look for any other such issues.

**Comment by shivshankar9** [comment]
I will do that..

**Comment by kshitija-2001** [comment]
Please assign me this issue under LGMSOC 21

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me this issue under LGMSOC 21

Already assigned.

**Comment by Deep06-11** [comment]
@QAZIMAAZARSHAD Can you please assign me this issue under LGM-SOC 21 if it's not complete yet

**Comment by QAZIMAAZARSHAD** [comment]
The first PR will be accepted.

**Comment by vk-2501** [comment]
Kindly assign me this issue
