### ISSUE TITLE
Integrate payment gateway in premium page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#359]

**Comment by kshitija-2001** [comment]
please assign me this issue under LGMSOC'21

**Comment by kshitija-2001** [comment]
Please may I know through which login email should I integrate the payment button?

**Comment by QAZIMAAZARSHAD** [comment]
> Please may I know through which login email should I integrate the payment button?

Do you need a password as well?

**Comment by kshitija-2001** [comment]
No, But a new password will be created and also a registered mobile number for accepting the payment

**Comment by QAZIMAAZARSHAD** [comment]
qazimaazarshad.info@gmail.com
8922075023

**Comment by kshitija-2001** [comment]
Ok thanks a lot

**Comment by kshitija-2001** [comment]
I am signing up on Razorpay they are asking for the verification code came on that mail id

**Comment by QAZIMAAZARSHAD** [comment]
209733
