### ISSUE TITLE
Create separate pages for movies of different regional languages  

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#36]
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Rishita11** [comment]
I would like to work on this. Please assign this to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@Rishita11 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by nandinimalik16** [comment]
I woul like to work on it. please assign me this issue

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 and @nandinimalik16 how is it going?

**Comment by saimanoharhm** [comment]
@coding-geek21  and @nandinimalik16  Any update guys

**Comment by nandinimalik16** [comment]
about to complete

**Comment by saimanoharhm** [comment]
> about to complete

ok cool

**Comment by nandinimalik16** [comment]
not able to create a pull request
![romance html - project9 - Visual Studio Code 7_9_2021 3_08_14 AM](https://user-images.githubusercontent.com/71604282/124994173-142fe780-e063-11eb-9f4c-17d742cac7e4.png)

**Comment by nandinimalik16** [comment]
I have Created the pull request. Please suggest if any changes are required.

**Comment by saimanoharhm** [comment]
> required.

cc: @QAZIMAAZARSHAD
