### ISSUE TITLE
Fix sign up form validation ( BUG )

### ISSUE THREAD

**Issue by Godwindaniel10** [QAZIMAAZARSHAD/Movie-Streaming-Website#364]
Sign-up form validation is not working as expected.   my password is 6 characters long and has a number and also has a lower case and an uppercase, but it's still displaying a form validation error.

As shown below.         

![movie-stream-bug](https://user-images.githubusercontent.com/54848535/123269046-81396e00-d4f6-11eb-8fab-b3b5bb1a78ea.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/123271848-dab59300-d51e-11eb-865c-3b6163089f21.png)

I tried it worked for every password except yours godwinFunc1000().

You can try fixing it.

**Comment by Godwindaniel10** [comment]
@QAZIMAAZARSHAD on it....

**Comment by saimanoharhm** [comment]
@Godwindaniel10 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Godwindaniel10** [comment]
@saimanoharhm , i am actually working on something at the moment, if you like to work on this issue, please feel free to go ahead .

Thank you for the reminder .

**Comment by saimanoharhm** [comment]
> @saimanoharhm , i am actually working on something at the moment, if you like to work on this issue, please feel free to go ahead .
> 
> Thank you for the reminder .

@Godwindaniel10 I am a mentor for this project so I don't have access to take up issue and work on. If you still want to continue you can else let us know will assign to someone else.
-Thanks

**Comment by Godwindaniel10** [comment]
oh aiit , you should assign the issue to someone else. i am a bit overwhelmed at the moment.

thanks @saimanoharhm

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by saimanoharhm** [comment]
> Can I work on this issue?

cc : @QAZIMAAZARSHAD

**Comment by saimanoharhm** [comment]
> Can I work on this issue?

Yes you can

**Comment by KHemanthRaju** [comment]
Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue?

Already assigned.
If it remains unresolved for a few more days then I will assign you.

**Comment by QAZIMAAZARSHAD** [comment]
@ujju20 figured out the issue?

Any updates?
