### ISSUE TITLE
Make slideshow continuous and it should always be visible on screen

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#368]
![image](https://user-images.githubusercontent.com/56196640/123300628-5ff97180-d538-11eb-8a08-df9331bade20.png)

This is the case when the website opens, slideshow must not be hidden at any point of time.

**Comment by aasthasaxena217** [comment]
I can make bootstrap carousel , where it will show multiple images continuously or remove the bugs in existing code.

**Comment by QAZIMAAZARSHAD** [comment]
> I can make a bootstrap carousel, where it will show multiple images continuously(slide show) or remove the bugs in existing code.

As you wish, but it should be automatic, continuously moving, and must be responsive.

**Comment by aasthasaxena217** [comment]
Yes, please assign this issue to me

**Comment by saimanoharhm** [comment]
@aasthasaxena217 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by aasthasaxena217** [comment]
@saimanoharhm , the issue effect is made properly and I have createdclasses to div tags, because marquee tag does not have the continous effect property , but my problem is that , it is having little black space between the images , which i am not able to remove it . This is responsive. 
![image](https://user-images.githubusercontent.com/64476429/125023768-2b8bc680-e09d-11eb-97dd-be674d21bbef.png)

**Comment by QAZIMAAZARSHAD** [comment]
> @saimanoharhm , the issue effect is made properly and I have created classes to div tags, because marquee tag does not have the continuous effect property , but my problem is that , it is having little black space between the images , which i am not able to remove it . This is responsive.
> ![image](https://user-images.githubusercontent.com/64476429/125023768-2b8bc680-e09d-11eb-97dd-be674d21bbef.png)

@aasthasaxena217 third row is not entirely visible so remove that row for this window size and increase the size of images so they fit the entire screen.

**Comment by aasthasaxena217** [comment]
@QAZIMAAZARSHAD sure , will do this

**Comment by aasthasaxena217** [comment]
@QAZIMAAZARSHAD  and @saimanoharhm , Is this fine? can I make pull request ? ![image](https://user-images.githubusercontent.com/64476429/125029270-ff754300-e0a6-11eb-9c03-01bc596df1a7.png)

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD and @saimanoharhm , Is this fine? can I make pull request ? ![image](https://user-images.githubusercontent.com/64476429/125029270-ff754300-e0a6-11eb-9c03-01bc596df1a7.png)

Check responsiveness as well.

If everything is fine then make PR.

**Comment by QAZIMAAZARSHAD** [comment]
@aasthasaxena217 would you like to resolve the issue or should I assign someone else?

**Comment by aasthasaxena217** [comment]
@QAZIMAAZARSHAD I want to resolve this issue , I am working on that

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Comment by aasthasaxena217** [comment]
@QAZIMAAZARSHAD , Sorry, but I tried a lot on this to make that work , and using my code to make slide show is disturbing the existing code of register section . To make the slide continuous , I have to write the whole code again including register section of landing page. I think you should assign this issue to someone better.

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Comment by dilroseR** [comment]
Can i know what is the issue?

**Comment by dilroseR** [comment]
As i can see slideshow is happening on the website

**Comment by QAZIMAAZARSHAD** [comment]
> As i can see slideshow is happening on the website

When website opens it starts like this and also ends with a black screen.
![image](https://user-images.githubusercontent.com/56196640/126036250-e9dd61f3-cf05-4b28-a703-7abda132ef56.png)

It should always be active on screen and continuous.

**Comment by dilroseR** [comment]
Can i try this?

**Comment by dilroseR** [comment]
> > As i can see slideshow is happening on the website
> 
> When website opens it starts like this and also ends with a black screen.
> ![image](https://user-images.githubusercontent.com/56196640/126036250-e9dd61f3-cf05-4b28-a703-7abda132ef56.png)
> 
> It should always be active on screen and continuous.

but when the list once ends balck screen will be seen and again it will start

**Comment by QAZIMAAZARSHAD** [comment]
Yes, you have to correct that ending part as well.

See in the home page slideshow is fine.

**Comment by dilroseR** [comment]
> Yes, you have to correct that ending part as well.
> 
> See in the home page slideshow is fine.

okay.. i'll try solving this

**Comment by dilroseR** [comment]
Sorry @QAZIMAAZARSHAD I'm not able to solve the issue

**Comment by QAZIMAAZARSHAD** [comment]
@dilroseR you want any help or do you no longer want to work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
@ishi0301 and @saimanoharhm look into this.

Help contributors resolve this issue.

**Comment by dilroseR** [comment]
> @dilroseR you want any help or do you no longer want to work on this issue?

i need help

**Comment by QAZIMAAZARSHAD** [comment]
@ishi0301 and @saimanoharhm look into this.
