### ISSUE TITLE
Design TV page 

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#37]
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

**Comment by manognyaa** [comment]
i would likw work on this issue please assign it to me @QAZIMAAZARSHAD @coding-geek21

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

**Comment by manognyaa** [comment]
Hello sir,

As after 10th june the contribution period counts. Can I pull request the
issue on 10th june itself please ?

Please take my request into consideration

**Comment by manognyaa** [comment]
> Go ahead.

thank you sir

**Comment by coding-geek21** [comment]
> Go ahead.

Can you please tell who should work, Because i created this issue

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 and @manognyaa both of you can work on this issue. I'll accept the best design or you both can improve or fix bugs in each others design when I will merge first PR.

**Comment by manognyaa** [comment]
> @coding-geek21 and @manognyaa both of you can work on this issue. I'll accept the best design or you both can improve or fix bugs in each others design when I will merge first PR.

Definitely sir, thank you :)

**Comment by coding-geek21** [comment]
> @coding-geek21 and @manognyaa both of you can work on this issue. I'll accept the best design or you both can improve or fix bugs in each others design when I will merge first PR.

sure ,Thank you :)

**Comment by manognyaa** [comment]
hello sir,
I have completed my design. pls verify it and let me know changes if needed. I am ready to rectify it :) @QAZIMAAZARSHAD 
my design link : https://www.figma.com/file/OvNhjZwi2puRmR1EQuCc66/Untitled?node-id=0%3A1

**Comment by QAZIMAAZARSHAD** [comment]
> hello sir,
> I have completed my design. pls verify it and let me know if any changes needed. I am ready to rectify it :) @QAZIMAAZARSHAD
> my design link: https://www.figma.com/file/OvNhjZwi2puRmR1EQuCc66/Untitled?node-id=0%3A1

Its nice,
Keep in mind the color and theme of this website. 
Use a simple font family.

**Comment by manognyaa** [comment]
> > hello sir,
> > I have completed my design. pls verify it and let me know if any changes needed. I am ready to rectify it :) @QAZIMAAZARSHAD
> > my design link: https://www.figma.com/file/OvNhjZwi2puRmR1EQuCc66/Untitled?node-id=0%3A1
> 
> Its nice,
> Keep in mind the color and theme of this website.
> Use a simple font family.

Sure sir, thank you :) @QAZIMAAZARSHAD

**Comment by SanjeevKumar22** [comment]
I improved Index page and Tv page please assign me and create for PR

**Comment by QAZIMAAZARSHAD** [comment]
> I improved Index page and Tv page please assign me and create for PR

Since other contributors are also working on this issue only the best design will be accepted.

**Comment by nik464** [comment]
I have improved tv page .Please assign this issue I am just a beginner at lgm-soc.

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 and @manognyaa you can open new issues if you believe your design is better.
