### ISSUE TITLE
Add preloader to the website

### ISSUE THREAD

**Issue by mdinesh124** [QAZIMAAZARSHAD/Movie-Streaming-Website#370]
I would add preloader to the website which loads before opening of the movie-streaming-website.

**Comment by mdinesh124** [comment]
@QAZIMAAZARSHAD Please assign me this issue under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
@mdinesh124 preloader already existed but due to an update, something went wrong, look into it.

**Comment by mdinesh124** [comment]
Ok

**Comment by QAZIMAAZARSHAD** [comment]
@mdinesh124 are you on it?

**Comment by saimanoharhm** [comment]
@mdinesh124 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by mdinesh124** [comment]
I have added the preloader in the website but I am trying to improve its transition effects part. I will create a pull request by tomorrow positively.

**Comment by saimanoharhm** [comment]
> I have added the preloader in the website but I am trying to improve its transition effects part. I will create a pull request by tomorrow positively.

Ok Cool
