### ISSUE TITLE
Improve the landing page

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Movie-Streaming-Website#376]
Want to change the position of the front page and continuous sliding images.
Please assign me this issue.

**Comment by vk-2501** [comment]
Can I work on this issue?

**Comment by vk-2501** [comment]
Could you please provide a description what changes need to be done?

**Comment by QAZIMAAZARSHAD** [comment]
> Could you please provide a description what changes need to be done?

Just implement your own ideas to make the design better, refer to some other websites if you want to.

**Comment by vk-2501** [comment]
Okay thanks

**Comment by saimanoharhm** [comment]
@vk-2501 @tjanhvi Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by vk-2501** [comment]
Yes I have implemented navbar and logo and in background I want to set movies images with help of slider. But the image is not getting fit in background

**Comment by saimanoharhm** [comment]
@vk-2501 Share your code and screenshots about what do you want to do. I will help you out.

**Comment by tjanhvi** [comment]
> @vk-2501 @tjanhvi Any update? If you face issue in the code let me know with your problem I am here to help you out.

yaa sure there is problem that i'm not make the register button responsive but i changed the look of landing page

**Comment by saimanoharhm** [comment]
@tjanhvi and @vk-2501  Ok.  Push your code to origin but don't make a PR and share the link to it and share screenshot that which button is not getting for you..

**Comment by tjanhvi** [comment]
> @tjanhvi and @vk-2501 Ok. Push your code to origin but don't make a PR and share the link to it and share screenshot that which button is not getting for you..

ohh before seeing your comment i have dn the pr

**Comment by tjanhvi** [comment]
> @tjanhvi and @vk-2501 Ok. Push your code to origin but don't make a PR and share the link to it and share screenshot that which button is not getting for you..

Can we do one thing if my pr is ok then generate your issue on that.

**Comment by vk-2501** [comment]
I have also implemented hamburger menu for mobile view toggling.But it isn't working

**Comment by vk-2501** [comment]
So can i share the code ?

**Comment by QAZIMAAZARSHAD** [comment]
> I have also implemented hamburger menu for mobile view toggling.But it isn't working

This issue is for improving the landing page where have you added the hamburger menu?
Share screenshots and code.

**Comment by saimanoharhm** [comment]
> > @tjanhvi and @vk-2501 Ok. Push your code to origin but don't make a PR and share the link to it and share screenshot that which button is not getting for you..
> 
> Can we do one thing if my pr is ok then generate your issue on that.

Cc: @QAZIMAAZARSHAD

**Comment by vk-2501** [comment]
![image](https://user-images.githubusercontent.com/73028420/125159219-bcdd6480-e193-11eb-9711-80894b3b5675.png)

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/125161634-14ce9800-e1a1-11eb-8edd-bb60b0419f8b.png)


This is the current landing page, the purpose of this issue is to come up with a new and better design.
