### ISSUE TITLE
Improve footer in Login and sign-up  page 

### ISSUE THREAD

**Issue by puneetkaur2929** [QAZIMAAZARSHAD/Movie-Streaming-Website#379]
Hey @QAZIMAAZARSHAD 

As you can see the bottom class in Sign In page is not up to the mark .
I wish to work on this issue under LGM SOC '21
![Screenshot (52)](https://user-images.githubusercontent.com/80326308/123502573-1b222780-d66b-11eb-8b83-7673a605ca14.png)

**Comment by QAZIMAAZARSHAD** [comment]
Do it for both login and sign up page.
