### ISSUE TITLE
Button improvement !

### ISSUE THREAD

**Issue by Sarthakjain594** [QAZIMAAZARSHAD/Movie-Streaming-Website#381]
Heyy , I want to improve the buttons on the landing page and other pages . I am a LGM SOC'21 participant . 
Can I work on this ?

**Comment by QAZIMAAZARSHAD** [comment]
> Heyy , I want to improve the buttons on the landing page and other pages . I am a LGM SOC'21 participant .
> Can I work on this ?

Can you share what improvements you want to make?

**Comment by Sarthakjain594** [comment]
Actually I want to make improvement in its hover state , Like when we hover the button will have a border and changed text color to red i.e, button colour and a border of same color . 
It will be more appealing and feels more smooth .

**Comment by Sarthakjain594** [comment]
Should I make the button color changes to read and bg color to white on hover as done for back to top button ?

**Comment by QAZIMAAZARSHAD** [comment]
Sure if it looks better.

**Comment by Sarthakjain594** [comment]
Heyyy To imrpove the buttons , I need to remove the bootstrap from them and use custom CSS . Can I ??

**Comment by QAZIMAAZARSHAD** [comment]
> Heyyy To imrpove the buttons , I need to remove the bootstrap from them and use custom CSS . Can I ??

Sure,

Make sure you are not damaging any other feature and design.

**Comment by Sarthakjain594** [comment]
yes I will make sure that .
