### ISSUE TITLE
Apply custom scroll bar in login and signup page, improve scroll to top button hover effect

### ISSUE THREAD

**Issue by Sarthakjain594** [QAZIMAAZARSHAD/Movie-Streaming-Website#382]
Heyy , I am a LGM SOC'21 participant . Back to top has absolute position on the web pages . However it should be fixed on the bottom of view port and can't be disappeared on scrolling . 

I would like to rectify this thing . Can I ?

**Comment by QAZIMAAZARSHAD** [comment]
Do it in all pages.

Also apply hover effect on it.

**Comment by Sarthakjain594** [comment]
Okay . Thanks sir . I will .

**Comment by QAZIMAAZARSHAD** [comment]
@Sarthakjain594 scroll to top button is already fixed on the footer.

I misunderstood, I thought this issue is open in my other project. My apology.

Scroll to top button is fine.

**Comment by QAZIMAAZARSHAD** [comment]
You can still do one thing,

Make scroll to top button in signup and login page similar to that in other pages.
Also apply custop scroll bar in login and signup page as in other pages.

And change hover effect of the scroll button on all pages.
On hover - Background white, inside red

**Comment by QAZIMAAZARSHAD** [comment]
![Screenshot (173)](https://user-images.githubusercontent.com/56196640/123513203-6d823900-d6a9-11eb-949a-52272a13c919.png)

**Comment by Sarthakjain594** [comment]
OKkk no worries ... I will do that .

**Comment by Sarthakjain594** [comment]
But still I wanna ask one thing , correct me if I am thinking in some wrong direction .
The back to top button on all pages is gonna be on the footer itself .
Then how could it be managable to scroll so long to top again from the mid of  a page ,  if the button is in the end and not visible there in the mid ?

**Comment by QAZIMAAZARSHAD** [comment]
> But still I wanna ask one thing , correct me if I am thinking in some wrong direction .
> The back to top button on all pages is gonna be on the footer itself .
> Then how could it be managable to scroll so long to top again from the mid of a page , if the button is in the end and not visible there in the mid ?

It is better this way, it was that way previously but changed because it was not looking nice.
Also, not all pages are too long, so it won't be that much difficult.

**Comment by Sarthakjain594** [comment]
Okk I got it
