### ISSUE TITLE
List of movies ranging according to their popularity and acceptance rate

### ISSUE THREAD

**Issue by arnab8335** [QAZIMAAZARSHAD/Movie-Streaming-Website#389]
Pease assign this to me as a part of LGMSoC 21

**Comment by saimanoharhm** [comment]
@arnab8335 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by arnab8335** [comment]
@saimanoharhm can I implement the star rating in the website.

**Comment by saimanoharhm** [comment]
> @saimanoharhm can I implement the star rating in the website.

cc: @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> @saimanoharhm can I implement the star rating in the website.

Go ahead

**Comment by QAZIMAAZARSHAD** [comment]
@arnab8335 any update?

**Comment by aditya687** [comment]
Please assign me @QAZIMAAZARSHAD . I will make list of movies based on their performance.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me @QAZIMAAZARSHAD . I will make list of movies based on their 

First, resolve other issues that are assigned to you.
