### ISSUE TITLE
Redesign search bar button

### ISSUE THREAD

**Issue by manognyaa** [QAZIMAAZARSHAD/Movie-Streaming-Website#39]
hello sir,
My idea is all about to improve the search box button. If we see the search box button it is purely simple. I would like to contribute some changes to the search box button. 
Normally, the search box button will appear like a circle and between the circle the search symbol in it. whenever a person wants to hover the cursor the circle search box will turn into a rectangle one where the user can search.
trust me sir it will be amazing :)

please assign this to me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by manognyaa** [comment]
> I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Thank you sir :)

**Comment by QAZIMAAZARSHAD** [comment]
@manognyaa are you working on this?

**Comment by mehulmb1** [comment]
Please let me do this I will make a responsive button and also gonna add animation to it.

**Comment by QAZIMAAZARSHAD** [comment]
> Please let me do this I will make a responsive button and also gonna add animation to it.

Do it for every page.
Don't damage other features.
Check responsiveness as well.

**Comment by QAZIMAAZARSHAD** [comment]
@mehulmb1 and @manognyaa are you guys on it?

**Comment by saimanoharhm** [comment]
@mehulmb1  and @manognyaa Any update guys
