### ISSUE TITLE
Fix the footer of FAQ page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#390]

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue under LGMSoc'21

**Comment by saimanoharhm** [comment]
@JahnaviKashyap19 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Garima-7** [comment]
Assign this to me pls.

**Comment by QAZIMAAZARSHAD** [comment]
> Assign this to me pls.

DCP?

**Comment by Garima-7** [comment]
> > Assign this to me pls.
> 
> DCP?

Yes

**Comment by Garima-7** [comment]
https://garima-7.github.io/Movie-Streaming-Website/
is is fine now?
