### ISSUE TITLE
Design Anime page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#391]

**Comment by JahnaviKashyap19** [comment]
please assign me this issue under LGMSoc'21

**Comment by QAZIMAAZARSHAD** [comment]
@JahnaviKashyap19 flip effect, nav bar, and footer should be similar to other pages.

**Comment by JahnaviKashyap19** [comment]
> @JahnaviKashyap19 flip effect, nav bar, and footer should be similar to other pages.

Okay.

**Comment by Srijan1878** [comment]
Can I work on this issue? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Already assigned.

**Comment by saimanoharhm** [comment]
@JahnaviKashyap19 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Srijan1878** [comment]
Hello, in case she misses out on the task, please consider me as an assignee. @QAZIMAAZARSHAD

**Comment by JahnaviKashyap19** [comment]
> @JahnaviKashyap19 Any update? If you face issue in the code let me know with your problem I am here to help you out.

I am working on it. It should be done by today.
