### ISSUE TITLE
Trailer window should open within the website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#392]
Currently, when the trailer button is clicked the user is redirected to youtube, but instead a small or medium size window should open within the website to view the trailer.

**Comment by JahnaviKashyap19** [comment]
Please assign me this issue.

**Comment by saimanoharhm** [comment]
@JahnaviKashyap19 Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by JahnaviKashyap19** [comment]
> @JahnaviKashyap19 Any update? If you face issue in the code let me know with your problem I am here to help you out.

Thank you I am working on it and I will reach out incase I'm stuck

**Comment by JahnaviKashyap19** [comment]
@saimanoharhm I am having difficulty with this issue. I created a modal so that on clicking on the trailer button the video appears on the modal but nothing is appearing.

**Comment by QAZIMAAZARSHAD** [comment]
@JahnaviKashyap19 issue resolved or not?

@ish-0709 help @JahnaviKashyap19 in this issue.

**Comment by akshay399** [comment]
@QAZIMAAZARSHAD assign me this issue

**Comment by aditya687** [comment]
Please assign me this issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@akshay399 and @JahnaviKashyap19 any updates?

**Comment by dilroseR** [comment]
can i try this?

**Comment by dilroseR** [comment]
in which html page?

**Comment by QAZIMAAZARSHAD** [comment]
> in which html page?

Currently, whenever a trailer button is clicked it redirects to youtube or IMDB, but instead, a medium-size window should pop-up whenever the trailer button is clicked.

You have to do this for every single card on every page.
Web-series and kids page have not been updated yet, you can skip those.

**Comment by dilroseR** [comment]
https://user-images.githubusercontent.com/70878223/127742305-5a14d6a6-abcc-4761-9763-c839629397f2.mp4

is it ok like this if i implement this on every card?

**Comment by QAZIMAAZARSHAD** [comment]
Better than before.

But if you can improve the design and size of the window then it will be better.
