### ISSUE TITLE
Design a new creative logo for website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#4]
The name of the website is **ApnaTheatre**. 
Don't change the name of the website, you can come up with an interesting slogan.

Use red and black color so it matches the website's theme.

**Comment by adampavel** [comment]
Hey, can I start working on this?

**Comment by QAZIMAAZARSHAD** [comment]
I will assign you this issue when the contribution period starts from 10 June, then you can start working on this issue.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
Sure,

I will assign you this issue when the contribution period starts from 10 June, then you can start working on this issue.

**Comment by BeginnerCoder21** [comment]
Can I work on this, I am a graphic designer also I'm a participant of LGM-Soc'21.

**Comment by QAZIMAAZARSHAD** [comment]
@BeginnerCoder21 sure, go-ahead

I will assign you this issue when the contribution period starts from 10 June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure, @Ayushi7456 go ahead.

**Comment by RakeshCharpe** [comment]
I would like to work on this issue ,can I work on this issue I am a participant of LCM Soc21

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue, can I work on this issue I am a participant of LCM Soc21

Sure, go ahead

**Comment by Nikhita28** [comment]
I would like to work on this under lgmsoc 2021

**Comment by Astitva7717** [comment]
please assign me this task (if you thinks it will enhance your project) under the Lgm-Soc'21

**Comment by Charvi-Bansal** [comment]
Can I start working on this now?

**Comment by starrohan999** [comment]
hii @QAZIMAAZARSHAD  here is my logo that suits Ui of the website.
![Apna Theater](https://user-images.githubusercontent.com/71714344/121477725-d436ff80-c9e5-11eb-946f-d706bb8f1348.png)

**Comment by starrohan999** [comment]
Please tell me how is it and or any kind improvements as well.

**Comment by Jagannath8** [comment]
![logo](https://user-images.githubusercontent.com/64650848/121479603-d306d200-c9e7-11eb-9479-db0f330a991f.gif)

This is the logo I've designed

**Comment by starrohan999** [comment]
Great

**Comment by Ayushi7456** [comment]
Can i create PR or the issue has resolved?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I create PR or the issue has resolved?

Don't make any PR's.

You are welcome to show your design. The best logo design will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
> ![logo](https://user-images.githubusercontent.com/64650848/121479603-d306d200-c9e7-11eb-9479-db0f330a991f.gif)
> 
> This is the logo I've designed

Nice,

Others are also working let's wait and see their designs.

**Comment by QAZIMAAZARSHAD** [comment]
> hii @QAZIMAAZARSHAD here is my logo that suits Ui of the website.
> ![Apna Theater](https://user-images.githubusercontent.com/71714344/121477725-d436ff80-c9e5-11eb-946f-d706bb8f1348.png)

Nice, It would be better if it had some catchy slogan.

**Comment by RakeshCharpe** [comment]
Can we show the logo design here ?

**Comment by starrohan999** [comment]
Sure @QAZIMAAZARSHAD

**Comment by starrohan999** [comment]
@QAZIMAAZARSHAD  
here i add slogon
![Uploading Apna Theater (1).png…]()

**Comment by RakeshCharpe** [comment]
Here is my two logo design ....

**Comment by RakeshCharpe** [comment]
![20210610_132317_0000.png](https://user-images.githubusercontent.com/69101908/121497900-86c48d80-c9f9-11eb-909d-78a33a4f250d.png)
![20210610_132521_0000.png](https://user-images.githubusercontent.com/69101908/121497920-8b894180-c9f9-11eb-81dc-31f298f465ba.png)




Here is my two logo design....

**Comment by Charvi-Bansal** [comment]
![Apna theatre (2)](https://user-images.githubusercontent.com/77285977/121513562-9ac3bb80-ca08-11eb-88a9-aed9913af93a.png)

Here is my logo :)

**Comment by QAZIMAAZARSHAD** [comment]
Cool @RakeshCharpe and @Charvi-Bansal .

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD
> here i add slogon

not visible @starrohan999.

**Comment by starrohan999** [comment]
![Apna Theater (1)](https://user-images.githubusercontent.com/71714344/121523067-6d303f80-ca13-11eb-8843-7dd7aa3a563c.png)

**Comment by starrohan999** [comment]
@QAZIMAAZARSHAD  here it is.

**Comment by QAZIMAAZARSHAD** [comment]
Nice...

**Comment by BeginnerCoder21** [comment]
Here is my logo 
![TheaterLogo](https://user-images.githubusercontent.com/60263821/121530372-fb5bf400-ca1a-11eb-9e9e-5dda9f762061.png)

PDF file : [TheaterLogo.pdf](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/files/6631611/TheaterLogo.pdf)

**Comment by BeginnerCoder21** [comment]
Here is my Logo
![TheaterLogo](https://user-images.githubusercontent.com/60263821/121530855-7a512c80-ca1b-11eb-9801-84c0e2498f64.png)
PDF file : [TheaterLogo.pdf](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/files/6631647/TheaterLogo.pdf)

**Comment by QAZIMAAZARSHAD** [comment]
Awesome @BeginnerCoder21

**Comment by Nikhita28** [comment]
Here are the two logo designs that I came up with :)
![Apna theatre](https://user-images.githubusercontent.com/73106734/121540185-e59efc80-ca23-11eb-8811-48e177b565f9.png)

![Apna theatre (1)](https://user-images.githubusercontent.com/73106734/121540236-f2bbeb80-ca23-11eb-8c09-b5c2655cf57a.png)

**Comment by QAZIMAAZARSHAD** [comment]
Very nice @Nikhita28

**Comment by Ayushi7456** [comment]
I made this one.
![Apna Theatre3-01](https://user-images.githubusercontent.com/78416191/121586876-1e58ba80-c9bf-11eb-9b58-31f4909b496c.png)

**Comment by Ayushi7456** [comment]
I made this one.
![Apna Theatre4-01](https://user-images.githubusercontent.com/78416191/121587188-742d6280-c9bf-11eb-9ea5-32cb586186d6.png)

**Comment by QAZIMAAZARSHAD** [comment]
Cool @Ayushi7456

**Comment by kshitija-2001** [comment]
I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.

**Comment by kshitija-2001** [comment]
I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.

@kshitija-2001 this issue has already been resolved.

**Comment by Charvi-Bansal** [comment]
> > I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.
> 
> @kshitija-2001 this issue has already been resolved.

I want to ask this issue #4 has been resolved? But its still open ..Pls clarify

**Comment by QAZIMAAZARSHAD** [comment]
> > > I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.
> > 
> > 
> > @kshitija-2001 this issue has already been resolved.
> 
> I want to ask this issue #4 has been resolved? But its still open ..Pls clarify

This issue is still open for those who were assigned for this issue.
@Charvi-Bansal you can show your design.

The best logo will be accepted.

**Comment by Charvi-Bansal** [comment]
> > > > I would like to work on this issue , can I work on this issue I am a participant of LCM Soc21.
> > > 
> > > 
> > > @kshitija-2001 this issue has already been resolved.
> > 
> > 
> > I want to ask this issue #4 has been resolved? But its still open ..Pls clarify
> 
> This issue is still open for those who were assigned for this issue.
> @Charvi-Bansal you can show your design.
> 
> The best logo will be accepted.

I have posted my design :) Thanks for clarifying.

**Comment by QAZIMAAZARSHAD** [comment]
@BeginnerCoder21, @Jagannath8, @RakeshCharpe, @starrohan999, @Nikhita28, @Astitva7717, @Charvi-Bansal, @Ayushi7456, @adampavel.

You all can make PR now.

Don't do any changes in code.
Just create a folder named "Logo" in the Images folder and add your logo in that folder.

**Comment by starrohan999** [comment]
Sure sir

**Comment by RakeshCharpe** [comment]
Sure sir

**Comment by Ayushi7456** [comment]
We have to add logo with or without background? And In which format we have to add the logo? png?

**Comment by QAZIMAAZARSHAD** [comment]
> We have to add a logo with or without a background? And In which format we have to add the logo? png?

Your wish.
It should be suitable to be used anywhere in this website.
