### ISSUE TITLE
Add filter to sort movies according to the genre

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Movie-Streaming-Website#40]
I saw that we are creating separate pages for each genres , this can be enhanced by using filters and this will reduce the number of webpages and displays based on filters using javascript in the same page itself

I would like to work on this issue @QAZIMAAZARSHAD ,please assign me

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea, go ahead.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by coding-geek21** [comment]
> Nice idea, go ahead.
> 
> I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Thank you :)

**Comment by QAZIMAAZARSHAD** [comment]
@coding-geek21 are you working on this?

**Comment by coding-geek21** [comment]
Yeah actually I was having exams, so was not able to contribute, I will be making a PR soon , just give me some more time

**Comment by saimanoharhm** [comment]
@coding-geek21 Any update
