### ISSUE TITLE
Fix google sign-in function in login page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#406]

**Comment by RituCs** [comment]
I would like to work on this issue.Please assign me.

**Comment by saimanoharhm** [comment]
@RituCs Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by RituCs** [comment]
Yes please actually I could not found the api key and the client id . Apart from that I also want to know where the google sign in button linked to the JS?

**Comment by saimanoharhm** [comment]
> api key and the client

I think api key and client id might have saved on .env file so it's visble for people who created it.  @QAZIMAAZARSHAD Who worked on login page before ?

**Comment by QAZIMAAZARSHAD** [comment]
@Akshit42-hue

**Comment by Akshit42-hue** [comment]
@RituCs api key and client id is in the login.html file above </head> tag

**Comment by Akshit42-hue** [comment]
@RituCs api key and client id is in the login.html file  above /head  tag
