### ISSUE TITLE
Changes in navbar & adding top button

### ISSUE THREAD

**Issue by SamikshaSankar** [QAZIMAAZARSHAD/Movie-Streaming-Website#41]
Navbar 
1. The navbar will stick to the top when you reach its scroll position
2. Change colour when user scroll. I mean in opacity

Top-button
button that becomes visible when the user starts to scroll the page

I work on this issue under LGM-SOC'21 participant..please assigned me

**Comment by QAZIMAAZARSHAD** [comment]
@SamikshaSankar these issues are already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33 and https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/18.

You can look for any other issues.
