### ISSUE TITLE
Create an AI Robot for Movie-Streaming-Website  queries and general QnA replier.

### ISSUE THREAD

**Issue by NidhiChaurasia** [QAZIMAAZARSHAD/Movie-Streaming-Website#410]
#**Create an AI Robot for Movie-Streaming-Website  queries and general QnA replier that could resolve any kind of issue regarding movie-search or Rating and Reviews of Movies.

**Comment by NidhiChaurasia** [comment]
@QAZIMAAZARSHAD  please Assign me this issue .I am  a LGM-SOC'21 participant and wants to contribute in this project. I want to make a Chatbot in Dialogflow.
Here is the Bot I have created 👍🏻-
https://bot.dialogflow.com/53e898d9-a118-4378-908f-177b32f5b34f

**Comment by QAZIMAAZARSHAD** [comment]
Yes great idea, I was about to open this issue.

**Comment by NidhiChaurasia** [comment]
Thanks @QAZIMAAZARSHAD I would be notifying you here as soon as I make ! 👍🏻

**Comment by saimanoharhm** [comment]
@NidhiChaurasia Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by NidhiChaurasia** [comment]
@QAZIMAAZARSHAD Please check this out till date :- https://bot.dialogflow.com/4d401275-793f-4bdf-a490-2e704712324a

Add this agent to your website by copying the code below :-
<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  chat-icon="https:&#x2F;&#x2F;encrypted-tbn0.gstatic.com&#x2F;images?q=tbn:ANd9GcS78IuestoS20dnwqPs3eSz4rP5R2eX3HVCZw&ampusqp=CAU"
  intent="WELCOME"
  chat-title="Apna-Theatre-Chatbot"
  agent-id="4d401275-793f-4bdf-a490-2e704712324a"
  language-code="en"
></df-messenger>

**Comment by NidhiChaurasia** [comment]
Add this agent to your website by copying the code below:


<iframe
    allow="microphone;"
    width="350"
    height="430"
    src="https://console.dialogflow.com/api-client/demo/embedded/4d401275-793f-4bdf-a490-2e704712324a">
</iframe>

**Comment by QAZIMAAZARSHAD** [comment]
Not working?

Every time answering "Sorry, can you say that again?

**Comment by QAZIMAAZARSHAD** [comment]
And where I have to add this code?

In any file?

**Comment by NidhiChaurasia** [comment]
I have taken the queries from this site to train my Chatbot:- 

https://www.hotdocs.ca/p/streaming-faqs
https://techforluddites.com/streaming-media-frequently-asked-questions/
https://sedonafilmfestival.com/virtual-streaming-faqs/

If you have any other suggestions then please tell me !

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD @saimanoharhm Sir, I have taken the queries from this site to train my Chatbot:-
> 
> https://www.hotdocs.ca/p/streaming-faqs
> https://techforluddites.com/streaming-media-frequently-asked-questions/
> https://sedonafilmfestival.com/virtual-streaming-faqs/
> 
> If you have any other suggestions then please tell me !

@NidhiChaurasia these questions are not that much related to our website.

Can you train the bot with some related questions and answers?

**Comment by NidhiChaurasia** [comment]
Ok Sir,I will inform you once I am done!

**Comment by NidhiChaurasia** [comment]
This is modified chatbot  Kindly view mentors :- 
https://bot.dialogflow.com/f58d0247-f57d-49aa-b4a2-dc8cc22a2faa

**Comment by NidhiChaurasia** [comment]
After integrating this code in website it will appear in corner of website 

<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  chat-icon="https:&#x2F;&#x2F;encrypted-tbn0.gstatic.com&#x2F;images?q=tbn:ANd9GcSOgb4rtp1tp4mv4flT-rMfJKJ9Wln9ZxhOQg&ampusqp=CAU"
  intent="WELCOME"
  chat-title="Apna-Theatre-bot"
  agent-id="f58d0247-f57d-49aa-b4a2-dc8cc22a2faa"
  language-code="en"
></df-messenger>

**Comment by NidhiChaurasia** [comment]
@QAZIMAAZARSHAD @saimanoharhm  Please review this code in the main website for 1/4 th screen preview :--

<iframe
    allow="microphone;"
    width="350"
    height="430"
    src="https://console.dialogflow.com/api-client/demo/embedded/f58d0247-f57d-49aa-b4a2-dc8cc22a2faa">
</iframe>

**Comment by QAZIMAAZARSHAD** [comment]
@NidhiChaurasia bot is referring to this website https://www.filmsite.org/allfilms.html

Change link to our website.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD @saimanoharhm Please review this code in the main website for 1/4 th screen preview :--
> 
> <iframe allow="microphone;" width="350" height="430" src="https://console.dialogflow.com/api-client/demo/embedded/f58d0247-f57d-49aa-b4a2-dc8cc22a2faa"> </iframe>

You add these codes in the website then make PR we will review it.
Also share website link so we can review your changes.

**Comment by NidhiChaurasia** [comment]
🙂 Sir please review this  website with my chatbot then I will make a PR for the same  :- 

http://127.0.0.1:5500/Movie-Streaming-Website/index.html

I have made necessary changes .Kindly see it 🙏🏻 !

This is my chatbot that I have created  :-    https://bot.dialogflow.com/f58d0247-f57d-49aa-b4a2-dc8cc22a2faa

Website code snippet of Bot :-  <iframe
    allow="microphone;"
    width="350"
    height="430"
    src="https://console.dialogflow.com/api-client/demo/embedded/f58d0247-f57d-49aa-b4a2-dc8cc22a2faa">
</iframe>


Alongwith the Icon Chatbot in the corner of website code snippet :-  

<script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
<df-messenger
  chat-icon="https:&#x2F;&#x2F;encrypted-tbn0.gstatic.com&#x2F;images?q=tbn:ANd9GcSOgb4rtp1tp4mv4flT-rMfJKJ9Wln9ZxhOQg&ampusqp=CAU"
  intent="WELCOME"
  chat-title="Apna-Theatre-bot"
  agent-id="f58d0247-f57d-49aa-b4a2-dc8cc22a2faa"
  language-code="en"
></df-messenger>



Uploading Apna-Theatre-bot - Brave 2021-07-14 16-31-32.mp4…

**Comment by QAZIMAAZARSHAD** [comment]
@NidhiChaurasia this "http://127.0.0.1:5500/Movie-Streaming-Website/index.html" is not the link.

Host your website somewhere like netify, Github pages, repl.it then share the link.

Also, the chatbot is again recommending the wrong link. Chatbot should recommend this link https://qazimaazarshad.github.io/Movie-Streaming-Website/.

Also, change the color theme of the chatbot from blue to red-black like in the website.

And I suggest no need of chatbot on the index page.
It should be on every page except the index page.

**Comment by NidhiChaurasia** [comment]
@QAZIMAAZARSHAD  please tell me which website to host?

Whether the Apna Theatre website with chatbot  or only the website that contains chatbot .

**Comment by QAZIMAAZARSHAD** [comment]
Push all the changes you have done to your branch then host your branch on GitHub pages to show the changes,

**Comment by QAZIMAAZARSHAD** [comment]
@NidhiChaurasia any updates?

**Comment by NidhiChaurasia** [comment]
@QAZIMAAZARSHAD  I have discussed with @saimanoharhm and made changes here 
https://github.com/NidhiChaurasia/Movie-Streaming-Website

Kindly review !

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I have discussed with @saimanoharhm and made changes here
> https://github.com/NidhiChaurasia/Movie-Streaming-Website
> 
> Kindly review !

First, fetch upstream your repo is not updated.

And share a live demo link.

**Comment by QAZIMAAZARSHAD** [comment]
@NidhiChaurasia any updates?

**Comment by NidhiChaurasia** [comment]
https://github.com/NidhiChaurasia/Movie-Streaming-Website  @QAZIMAAZARSHAD 
Kindly see this

**Comment by QAZIMAAZARSHAD** [comment]
> https://github.com/NidhiChaurasia/Movie-Streaming-Website @QAZIMAAZARSHAD
> Kindly see this

Not this @NidhiChaurasia share a live link like this https://qazimaazarshad.github.io/Movie-Streaming-Website/.

Deploy your website on GitHub pages or Netlify then share link.

**Comment by QAZIMAAZARSHAD** [comment]
And the PR which is mentioned here is not to my repo.

Also, your repo is 165 commits behind. Before starting to work on this issue fetch upstream and update your repo.

If you are stuck reach out to @ishi0301 or @saimanoharhm.

**Comment by NidhiChaurasia** [comment]
http://nidhichaurasia.me/New-Movie-Streaming-Website/login.html
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Check yourself everything is messed up.
![image](https://user-images.githubusercontent.com/56196640/128479494-968b3cb0-b12c-422d-84cc-26cc128cf34c.png)
![image](https://user-images.githubusercontent.com/56196640/128479545-50200ac7-66e3-4e48-8653-fe568555a879.png)
![image](https://user-images.githubusercontent.com/56196640/128479844-672f6e47-cb85-4fe0-a2bb-9c0faa997172.png)
![image](https://user-images.githubusercontent.com/56196640/128479983-20bf9f03-b432-4083-aa37-0097df8a2e53.png)

**Comment by QAZIMAAZARSHAD** [comment]
![Screenshot (146)](https://user-images.githubusercontent.com/56196640/128480257-6bfe5402-9e71-4597-94d2-103c0b41f421.png)

And change blue colour to red also change the image of the bot.

**Comment by QAZIMAAZARSHAD** [comment]
I suggest throw this work and create a new branch and make only the necessary changes.
