### ISSUE TITLE
Add responsiveness to contact us page

### ISSUE THREAD

**Issue by Ananya-Misra** [QAZIMAAZARSHAD/Movie-Streaming-Website#411]
Please assign this issue to me under LGMSOC.

![image](https://user-images.githubusercontent.com/70848031/124365266-72745900-dc64-11eb-90d2-05f082fd64db.png)

![image](https://user-images.githubusercontent.com/70848031/124365573-a2246080-dc66-11eb-97ab-5f199b7bc4df.png)

**Comment by saimanoharhm** [comment]
@Ananya-Misra Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by Ananya-Misra** [comment]
@saimanoharhm I will make the PR by tomorrow.
