### ISSUE TITLE
Add validation to the form in contactus.html

### ISSUE THREAD

**Issue by Ananya-Misra** [QAZIMAAZARSHAD/Movie-Streaming-Website#412]
Adding validation and preventing the collapsing of email on the input.

![Untitled](https://user-images.githubusercontent.com/70848031/124365435-9edca500-dc65-11eb-8307-3f4030928ed4.png)

**Comment by saimanoharhm** [comment]
@Ananya-Misra Any update? If you face issue in the code let me know with your problem I am here to help you out.

**Comment by 119kanika** [comment]
I will do this work please assign me for this.

**Comment by QAZIMAAZARSHAD** [comment]
> I will do this work please assign me for this.

Under DCP or LGMSoC?

**Comment by 119kanika** [comment]
Under DCP

**Comment by Sarthakjain594** [comment]
heyy , 
is this issue resolved ?? Can I be a helping hand in this issue ? and if no one is working on this one , can I do ??

**Comment by QAZIMAAZARSHAD** [comment]
> heyy ,
> is this issue resolved ?? Can I be a helping hand in this issue ? and if no one is working on this one , can I do ??

Sure, you can go ahead.

**Comment by QAZIMAAZARSHAD** [comment]
@Sarthakjain594 under DCP or LGMSoC?

**Comment by Sarthakjain594** [comment]
@QAZIMAAZARSHAD under LGMSoC .
