### ISSUE TITLE
How to watch movie

### ISSUE THREAD

**Issue by VenomFate-619** [QAZIMAAZARSHAD/Movie-Streaming-Website#415]
How can we watch movie it only have trailer as well as how can I watch it with my friend on different devices and location

**Comment by QAZIMAAZARSHAD** [comment]
@VenomFate-619 are you asking question or want to add this feature in website?

**Comment by VenomFate-619** [comment]
I had read the description and thought that this features are there , but I was - wrong ,so it is a question ❓

**Comment by QAZIMAAZARSHAD** [comment]
> I had read the description and thought that these features are there, but I was wrong, so it is a question ❓

Yaa, there is no option to watch movies right now. This is just a demo website and these features will be added in the future.
