### ISSUE TITLE
Make "Welcome To ApnaTheatre.com®" line visible when hovering on logo

### ISSUE THREAD

**Issue by SamikshaSankar** [QAZIMAAZARSHAD/Movie-Streaming-Website#42]
It make be visible till  right to left
![changes](https://user-images.githubusercontent.com/52104082/121025785-2815ce80-c7c3-11eb-931d-3b227ccbb61e.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by vishalps2606** [comment]
I would like to contribute to this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@vishalps2606 since this is an easy issue and other contributors are already working on it I cannot assign you this issue.
You can look for any other issue, or open new issues.

**Comment by QAZIMAAZARSHAD** [comment]
@SamikshaSankar Do one thing.

Due to an update the search bar has been shifted below navbar, try to put it back in place,

**Comment by SamikshaSankar** [comment]
![IMG_20210611_201411](https://user-images.githubusercontent.com/52104082/121704719-a2ab5a80-caf1-11eb-9a1e-718f4ab5287c.jpg)

See this the output of my 2 pr

**Comment by SamikshaSankar** [comment]
![2021-06-11 (2)](https://user-images.githubusercontent.com/52104082/121714689-b8be1880-cafb-11eb-9c7d-b614ee4db95c.png)

Now It's fine I think?..2 PR was right but due to search bar its shoes error..Let me know is it ok or not? Then I will create PR

**Comment by QAZIMAAZARSHAD** [comment]
> ![2021-06-11 (2)](https://user-images.githubusercontent.com/52104082/121714689-b8be1880-cafb-11eb-9c7d-b614ee4db95c.png)
> 
> Now It's fine I think?..2 PR was right but due to search bar its shoes error..Let me know is it ok or not? Then I will create PR

Perfect.

Create PR.

**Comment by QAZIMAAZARSHAD** [comment]
Try not to have any conflicts this time, first update your repository, then make the changes, then make PR.

**Comment by QAZIMAAZARSHAD** [comment]
> ![2021-06-11 (2)](https://user-images.githubusercontent.com/52104082/121714689-b8be1880-cafb-11eb-9c7d-b614ee4db95c.png)
> 
> Now It's fine I think?..2 PR was right but due to search bar its shoes error..Let me know is it ok or not? Then I will create PR

@SamikshaSankar your changes are not displaying the same output.
I am saying this again, first completely update your repository. See your repo doesn't have a custom scroll bar.
Make a separate updated branch then push only the necessary changes.

And before making PR review both live demo and code.

**Comment by SamikshaSankar** [comment]
@QAZIMAAZARSHAD please review
