### ISSUE TITLE
Adding all the available genres in the About Us in Readme.md

### ISSUE THREAD

**Issue by manasb15** [QAZIMAAZARSHAD/Movie-Streaming-Website#427]
Genres that are available on the platform can be added in the section in a bullet format to give an idea to the viewer of all the content available. Also, we can update the word 'movieholics' which is misspelled to cinephiles or movie lovers. 

@QAZIMAAZARSHAD please assign me this issue under DCP21 if you think it is a worthy update.

**Comment by QAZIMAAZARSHAD** [comment]
@manasb15 movieholics is not misspelled it is fine.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD it is written as 'movieocohlic's' 
shouldn't it be movieholics or movieocoholics? Or better yet a different word, cinephiles maybe?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD it is written as 'movieocohlic's'
> shouldn't it be movieholics or movieocoholics? Or better yet a different word, cinephiles maybe?

Ooo I thought it is written movieholics. My mistake.

Yes go ahead.
