### ISSUE TITLE
Fit in desktop-size

### ISSUE THREAD

**Issue by SamikshaSankar** [QAZIMAAZARSHAD/Movie-Streaming-Website#43]
Decrease size of container
![2](https://user-images.githubusercontent.com/52104082/121027130-5811a180-c7c4-11eb-9b44-5f365e9b970d.jpg)

I work on this issue under LGM-SOC'21 participant..please assigned me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@SamikshaSankar this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/1.

Before opening any issue make sure that any similar is not open.
