### ISSUE TITLE
Change the Genre Name of Suspense to Thriller

### ISSUE THREAD

**Issue by manasb15** [QAZIMAAZARSHAD/Movie-Streaming-Website#430]
Technically the genre is formally known as Thriller or Mystery Thriller, so I think it would be a good change in the GUI and documentation. 
@QAZIMAAZARSHAD Please let me know if you think this is a good idea.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

Do it in all pages.

**Comment by QAZIMAAZARSHAD** [comment]
Under DCP?

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Yes please, I forgot to mention. I wanted it under DCP21

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Files named suspense should be changed to thriller as well or only in pages?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Files named suspense should be changed to thriller as well or only in pages?

If you change the file name then you have to change the name everywhere it is linked.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD So will it get very buggy and complicated? Or should I just change it within pages only?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD So will it get very buggy and complicated? Or should I just change it within pages only?

No, nothing will change if you understand the entire website and do the necessary modifications.
It is up to you if you are willing to take up the challenge you suggested or just change it within pages or just leave it be "Suspence & Thriller" is also fine.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Can you label this Up for Grab? I want to try contributing to the code rather than documentation.
