### ISSUE TITLE
Create logout feature in website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#439]
Rename the login button in the navbar to log out.

When the log out button should be clicked, the user should be redirected to the login page and log in again to go back to the main website.

**Comment by HarshitPandey251** [comment]
I want to contribute in this issue under both LGMSOC and DCP

**Comment by utkarsh-ub** [comment]
> I want to contribute in this issue under both LGMSOC and DCP

@HarshitPandey251 updates?

**Comment by aditya687** [comment]
Please assign me the issue, I think it will take less time to change this @utkarsh-ub

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign me the issue, I think it will take less time to change this @utkarsh-ub

@aditya687 the logout feature should be functional.

**Comment by QAZIMAAZARSHAD** [comment]
@HarshitPandey251 are you working on it?

**Comment by dilroseR** [comment]
i'd like to take it up

**Comment by dilroseR** [comment]
this issue was closed right?
what happened then?

**Comment by dilroseR** [comment]
> Rename the login button in the navbar to log out.
> 
> When the log out button should be clicked, the user should be redirected to the login page and log in again to go back to the main website.

this is to be done?

**Comment by QAZIMAAZARSHAD** [comment]
> > Rename the login button in the navbar to log out.
> > When the log out button should be clicked, the user should be redirected to the login page and log in again to go back to the main website.
> 
> this is to be done?

Yes

**Comment by dilroseR** [comment]
> > > Rename the login button in the navbar to log out.
> > > When the log out button should be clicked, the user should be redirected to the login page and log in again to go back to the main website.
> > 
> > 
> > this is to be done?
> 
> Yes

in which page?

**Comment by QAZIMAAZARSHAD** [comment]
All pages you have to replace the login with logout in the navbar.

**Comment by dilroseR** [comment]
is it ok if i make the logout as a button?

**Comment by QAZIMAAZARSHAD** [comment]
> is it ok if i make the logout as a button?

Sure
