### ISSUE TITLE
Navigation bar and bottom to top button

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Movie-Streaming-Website#44]
Navigation bar must be stick to page so that one who is on bottom of page  can easily acess home movies webseries etc section and there must be a bottom to top button so that on clicking one can go to top of page .

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 these issues are already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33 and https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/18.

Before opening any issue please make sure that any similar issue is not already open.
