### ISSUE TITLE
Remove splash screen from website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#446]

**Comment by QAZIMAAZARSHAD** [comment]
Under DCP or LGMSoC?

**Comment by bhoskarpooja** [comment]
LGMSOC

**Comment by harshit-dugar** [comment]
If this bug is not resolved can I work on it @QAZIMAAZARSHAD

**Comment by harshit-dugar** [comment]
Can you tell me in which folder I will find this issue ?

**Comment by QAZIMAAZARSHAD** [comment]
> Can you tell me in which folder I will find this issue?

The splash screen appears every time user tries to reach the home page.
Check home.html.

**Comment by harshit-dugar** [comment]
Can I commit on a new branch named Home_issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Can I commit on a new branch named Home_issue @QAZIMAAZARSHAD

Sure. As you wish.

**Comment by harshit-dugar** [comment]
Now that splash os not coming . Direct Home page is coming

**Comment by harshit-dugar** [comment]
@QAZIMAAZARSHAD please review my PR #469

**Comment by QAZIMAAZARSHAD** [comment]
@harshit-dugar any updates?

**Comment by anupammaurya6767** [comment]
just remove the splash screen or add another interactive preloader?

**Comment by QAZIMAAZARSHAD** [comment]
> just remove the splash screen or add another interactive preloader?

Only remove the splash screen from the home page.
