### ISSUE TITLE
Add anime page in genres drop down list 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#448]
Do this on all pages

**Comment by VWRoli** [comment]
I would like to take this issue please.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to take this issue please.

Under DCP or LGMSoC?

**Comment by VWRoli** [comment]
> > I would like to take this issue please.
> 
> Under DCP or LGMSoC?

Sorry, but I don't know what any of those mean. Could you enlighten me please?

**Comment by QAZIMAAZARSHAD** [comment]
DCP and LGMSoC are open-source events. And this project is a part of these events.

You can register in these events if you want, links in the readme file. just click on the logo.
