### ISSUE TITLE
Correct the color of genre drop down list in kids page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#449]
![image](https://user-images.githubusercontent.com/56196640/125757928-7d9380c1-a390-4c77-bc38-df7794c350ab.png)

**Comment by the-macson** [comment]
add me in this problem

**Comment by QAZIMAAZARSHAD** [comment]
> add me in this problem

Under DCP or LGMSoC?

**Comment by the-macson** [comment]
it's my First contribution i don't know what is DCP and LGMSoC

**Comment by QAZIMAAZARSHAD** [comment]
> it's my First contribution I don't know what is DCP and LGMSoC

DCP and LGMSoC are open-source contribution programs and this project is part of these programs.

If you wish you can participate in these events links to these websites are in the readme of this project, just click on their logo.

**Comment by the-macson** [comment]
under LGMSoc
