### ISSUE TITLE
Apnathreatre.com must be responsive.

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Movie-Streaming-Website#45]
Responsive website is a website which adjust itself according to screen size so that all user can interact easily irrespective of there screen size .
![bug](https://user-images.githubusercontent.com/56637948/121081327-34694e00-c7fa-11eb-8f1c-7f0cadfb8be9.jpg)
this website must be responsive so that it content can adjust itself according to screen size .

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/2.

Before opening any issue please make sure that any similar issue is not already open.
