### ISSUE TITLE
Navbar of home page is Not responsive like page of Kids

### ISSUE THREAD

**Issue by the-macson** [QAZIMAAZARSHAD/Movie-Streaming-Website#452]
![Screenshot (2)](https://user-images.githubusercontent.com/71259159/125793687-200b55e1-6c19-429f-b61c-41b80c7cc6b2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/71259159/125793752-81a8211c-caff-4137-ba84-f0e57adf6e85.png)

**Comment by the-macson** [comment]
Assign me in this issue

**Comment by QAZIMAAZARSHAD** [comment]
> Assign me in this issue

Other issues are assigned to you first solve them.
