### ISSUE TITLE
Add zoom in/zoom out button

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Movie-Streaming-Website#46]

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 I don't think there is any need for a zoom in/zoom out button on this website.

But if you would like to add this feature then go ahead.
I'll accept this only if the design suits the website.

**Comment by jayant766** [comment]
Please assign me this issue under LGMSOC'21

**Comment by Sumit11081996** [comment]
@QAZIMAAZARSHAD please assign me this issue

**Comment by QAZIMAAZARSHAD** [comment]
Are you guys working on this?

**Comment by QAZIMAAZARSHAD** [comment]
Add this feature only in desktop view, not in mobile view.

**Comment by royalleads15** [comment]
okk sir , will give response in 2 to 3 days.

**Comment by saimanoharhm** [comment]
@royalleads15 @Sumit11081996 @jayant766 Any update guys
