### ISSUE TITLE
Change "hover effect on Nav bar" 

### ISSUE THREAD

**Issue by ankitmishra067** [QAZIMAAZARSHAD/Movie-Streaming-Website#47]
If we change hover effect on nav bar. like, when we hover on that icon than background of particular icon will gets change

**Comment by ankitmishra067** [comment]
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

**Comment by QAZIMAAZARSHAD** [comment]
@ankitmishra067 this issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33.

Before opening any new issue please always make sure that no other similar issue is already open.
