### ISSUE TITLE
Quality of movie

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Movie-Streaming-Website#48]
We can also specify the quality of movie in top right corner of every movie poster.

**Comment by QAZIMAAZARSHAD** [comment]
What do you mean by quality?
Picture quality or movie rating.

**Comment by QAZIMAAZARSHAD** [comment]
I don't think this is necessary to specify. Because every movie can be watched in both good and bad quality. Also, there is always an option to increase or decrease quality while watching.
No movie website and app specify on the homepage about the quality of the picture.
