### ISSUE TITLE
Side Navbar

### ISSUE THREAD

**Issue by 2024-SANDHYA** [QAZIMAAZARSHAD/Movie-Streaming-Website#483]
Making a side navbar instead of 3 buttons in the hero section @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
@2024-SANDHYA didn't understand which 3 bittons? which hero section?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA didn't understand which 3 buttons? which hero section?

@QAZIMAAZARSHAD  Want to add a sidebar like this 
![image](https://user-images.githubusercontent.com/75671152/127475778-40cecec1-d929-4b0a-b12a-6530fc34a603.png)


And shifting these three buttons in the sidemenu itself.
![image](https://user-images.githubusercontent.com/75671152/127475861-3519c893-ffa8-47ec-86b9-7a62f3e1e974.png)

**Comment by QAZIMAAZARSHAD** [comment]
@2024-SANDHYA these 3 are not buttons just design.

And navbar is not needed on this page.
