### ISSUE TITLE
Overlapping footer and picture cards

### ISSUE THREAD

**Issue by SamikshaSankar** [QAZIMAAZARSHAD/Movie-Streaming-Website#49]
![2021-06-08 (10)_LI](https://user-images.githubusercontent.com/52104082/121195462-3fb98980-c88d-11eb-9ec1-251d8d82856e.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by jayant766** [comment]
Hii, can I correct this bug?

**Comment by SamikshaSankar** [comment]
Please assign @QAZIMAAZARSHAD

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD  I corrected this bug while working on home page in issue #19 So please assign me also,

**Comment by QAZIMAAZARSHAD** [comment]
@SamikshaSankar and @jayant766 a PR for this issue has already been made which will likely close this issue.

You can look for any other issues.

**Comment by WayneHaworth** [comment]
As discussed please assign this to me.
