### ISSUE TITLE
Improve the footer design

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#5]
Design a new creative footer.

**Comment by aum-singhal** [comment]
I can work on this Issue If you allow
Please assign it to me if possible when LGM-SOC starts

Thanks 😊

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by Naman-Joshi-14** [comment]
Sir can I work on this issue. @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Sir can I work on this issue. @QAZIMAAZARSHAD

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Other participants are also willing to resolve this issue so If you want your pull request to be merged then your design should be better than the others.

**Comment by ekagrashukla** [comment]
Hi 👋 I'd like to work on this issue as a participant of LGM SOC21.

**Comment by tjanhvi** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue

This issue is already assigned to many participants and will be closed soon.
Look for any other issue.

**Comment by tjanhvi** [comment]
> > I would like to work on this issue
> 
> This issue is already assigned to many participants and will be closed soon.
> Look for any other issue.

okay :)
