### ISSUE TITLE
Change Font of the website to make it look more attractive 

### ISSUE THREAD

**Issue by amankumar11** [QAZIMAAZARSHAD/Movie-Streaming-Website#503]
Change the font family to make the website look more attractive

**Comment by QAZIMAAZARSHAD** [comment]
> Change the font family to make the website look more attractive

Go ahead.
But make sure, all the pages should have the same font.

**Comment by techakhil-me** [comment]
still open ?

**Comment by amankumar11** [comment]
Ok. i have started working 👍

**Comment by QAZIMAAZARSHAD** [comment]
> still open ?

Someone else is working on this issue.
Look for other open issues.

**Comment by amankumar11** [comment]
Font-1 (Montserrat)
![image](https://user-images.githubusercontent.com/67067864/135607288-208274bf-c296-4855-89a7-b3586cf31ebd.png)

Font-2 (Ubuntu)
![image](https://user-images.githubusercontent.com/67067864/135607393-5a632bd6-0576-4a8e-b5aa-05cf016b5f6f.png)

@QAZIMAAZARSHAD which font would you suggest?

**Comment by QAZIMAAZARSHAD** [comment]
Ubuntu looks nice.

**Comment by QAZIMAAZARSHAD** [comment]
Also, when you will make PR do share a deployment link so I can review your changes.
