### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#51]

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/7.

Before opening any issue make sure no other similar issue is already open.
