### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Movie-Streaming-Website#52]

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by kumarishalini6** [comment]
@V-Yeshwanth  I am requesting you to please create new issue because I am also a participant and it is tough to find issue for me too please 🙏🙏.

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

Use the new logo in the splash screen which is yet to be created https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/4.
Till then use any sample picture to work on this issue.

**Comment by kumarishalini6** [comment]
ok

**Comment by kshitija-2001** [comment]
I would like to work on this issue ,can I work on this issue I am a participant of LCM Soc21.

**Comment by kshitija-2001** [comment]
which logo we have to use for displaying?

**Comment by QAZIMAAZARSHAD** [comment]
> which logo we have to use for displaying?

Use the new logo in the splash screen which is yet to be created #4.
Till then use any sample picture to work on this issue.

**Comment by kshitija-2001** [comment]
ok

**Comment by nik464** [comment]
I would like to contribute to splash screen as LGM 2021 participant. I know html css and javascript. Please assign the work to me.

**Comment by nik464** [comment]
please can you assign me this work becuase it will actively participate . I am beginnerat LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
@kshitija-2001 You have created a separate page for the splash screen and have not linked it with any page.
And create something like this https://cdn.dribbble.com/users/164756/screenshots/14613561/media/7b2c77ab0a7d84665a5866335788e94e.gif.

Use this logo -> https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/TheaterLogo.png
