### ISSUE TITLE
News page image not showing and padding too small

### ISSUE THREAD

**Issue by jmeyu** [QAZIMAAZARSHAD/Movie-Streaming-Website#520]
In "Coming Soon", Sidharth Malhotra: 'Hope Shershaah inspires the youth, the way Vikram Batra did' movie image is not showing. Moreover, the page padding is too small.

**Comment by Pathholder1806** [comment]
Hey @jmeyu and @QAZIMAAZARSHAD !
The image for the movie is showing!

![image](https://user-images.githubusercontent.com/61896647/188309490-dbb82313-3aa3-4a98-9fb2-c745076fa8ff.png)

So I think image problem is already resolved. And if the padding is faulty then let me know. I would like to contribute to it😀
