### ISSUE TITLE
Flipping Card will also invert the Label of the movie

### ISSUE THREAD

**Issue by ChinZhengSheng** [QAZIMAAZARSHAD/Movie-Streaming-Website#521]
When hovering over the poster, the label of the poster flips with the card.

Now - 
![image](https://user-images.githubusercontent.com/56196640/188257899-381944ab-364d-49b8-9f73-4ce8447ba1d1.png)

How it should be - 
![image](https://user-images.githubusercontent.com/56196640/188257908-6bf927a8-5a6b-4613-a057-d6de791079c9.png)

Verify on all the pages (all genres pages).

**Comment by Pathholder1806** [comment]
Hey @QAZIMAAZARSHAD !
I would like to contribute to this issue. Kindly assign me this

**Comment by vydyas** [comment]
I can work on this issue as part of hacktoberfest.

**Comment by vydyas** [comment]
@QAZIMAAZARSHAD  issue is coming because of a `<div class="film"></div>` if we keep this in front and back problem getting resolved, but code duplication happening. Can we eliminate flip animation form film class? or film div should animate?

**Comment by vydyas** [comment]
there are soo many div's should I make changes in all the divs and raise PR?

**Comment by vydyas** [comment]
There are some pages flip is not working like movies.html. What about those?

**Comment by vydyas** [comment]
There are 207 poster divs in the complete code. Need to change in all places?

**Comment by vydyas** [comment]
I'll do it for home page in the issue. we can raise different PR's for different pages or else prone to error is high

**Comment by QAZIMAAZARSHAD** [comment]
Fine, Go ahead
