### ISSUE TITLE
Cursor hover color change

### ISSUE THREAD

**Issue by SayanSaha01** [QAZIMAAZARSHAD/Movie-Streaming-Website#53]
this will impart an interactive look to your website i want to work on this issue and have already made the changes

**Comment by V-Yeshwanth** [comment]
Hey @QAZIMAAZARSHAD I want to work on this issue

**Comment by SayanSaha01** [comment]
![Screenshot (143)](https://user-images.githubusercontent.com/75988493/121296867-fc076400-c90e-11eb-8da6-43fdb79d419f.png)

**Comment by QAZIMAAZARSHAD** [comment]
@SayanSaha01 another similar issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33.

These effects and features will be dealt with in that issue.
