### ISSUE TITLE
[improvement] Fix the alignement issue of the navbar in the home section so it can have a better UI.

### ISSUE THREAD

**Issue by abitsalihu** [QAZIMAAZARSHAD/Movie-Streaming-Website#530]
The first Picture is how it is currently, the second picture is how I fixed it, not something major just better looking aesthetically.
<img width="1437" alt="Screen Shot 2022-09-03 at 23 30 09" src="https://user-images.githubusercontent.com/94648837/188288290-80a848fd-5e2c-4df7-b0aa-f9e22d7770d7.png">
<img width="1437" alt="Screen Shot 2022-09-03 at 23 26 49" src="https://user-images.githubusercontent.com/94648837/188288291-542d5d92-7f71-4bb0-893d-e18c645039c0.png">

I would love to fix and push this if It can be assigned to me :)

**Comment by QAZIMAAZARSHAD** [comment]
Make sure the nav bars of all the pages are fixed.
