### ISSUE TITLE
Design description window when movie card is clicked

### ISSUE THREAD

**Issue by V-Yeshwanth** [QAZIMAAZARSHAD/Movie-Streaming-Website#54]

**Comment by QAZIMAAZARSHAD** [comment]
@V-Yeshwanth another issue with the hovering effect is open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/10.
Also, IMDB rating is mentioned on the movie card, no need for description.

**Comment by QAZIMAAZARSHAD** [comment]
But you can do one thing.

When clicking on a movie card a description window should open, it should contain a movie poster on the left side, and description, IMDB rating, languages available and play, download button on the right side.

**Comment by V-Yeshwanth** [comment]
Sure! And I am Going to provide a button for IMDB page of that movie for full complete description

**Comment by V-Yeshwanth** [comment]
Am i assigned for this issue .?

**Comment by QAZIMAAZARSHAD** [comment]
> Am I assigned for this issue .?

Yes, you can start your work.

**Comment by ish-0709** [comment]
Hi sir can I add play pause buttons on movie cards that are directly linked to the trailer of movies?
Kindly assign me this issue under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
> Hi sir can I add play pause buttons on movie cards that are directly linked to the trailer of movies?
> Kindly assign me this issue under LGMSOC.

When clicking on a movie card a description window should open, it should play the movie trailer on the left side, and description, IMDB rating, languages available and play, download button on the right side.

**Comment by ish-0709** [comment]
@QAZIMAAZARSHAD  Sir I tried this wanted to know if this looks good enough..?

https://user-images.githubusercontent.com/63011793/122194217-dcde7880-ceb2-11eb-8bc5-8d6dabb1a719.mp4

**Comment by QAZIMAAZARSHAD** [comment]
Great,

Apply this for every single movie image of every single page.

Then make PR.

**Comment by ish-0709** [comment]
@QAZIMAAZARSHAD 
Sir, I have done all the changes mentioned above and made a PR.
Please have a look.
