### ISSUE TITLE
Fixing the UI on hover of the social media icons in the footer. 

### ISSUE THREAD

**Issue by siddharthsinghvats** [QAZIMAAZARSHAD/Movie-Streaming-Website#540]
Hovering on any of the icons in the footer applies the hover effect on all of them. Separating each icon to show the effect individually will enhance the UI.

**Comment by siddharthsinghvats** [comment]
Can I fix it?

**Comment by anupammaurya6767** [comment]
https://movie-streaming-website-omega.vercel.app/
