### ISSUE TITLE
Bug: Trailer links missing

### ISSUE THREAD

**Issue by amann-k** [QAZIMAAZARSHAD/Movie-Streaming-Website#541]
can i work on this

**Comment by neeraj542** [comment]
can i work on this issue

**Comment by ACAnyasodor** [comment]
can i work on this issue too?

**Comment by arpitstelin** [comment]
can i work on this issue too??

**Comment by Shikhar2702** [comment]
Hey @QAZIMAAZARSHAD i am interested to work on this project can you assign me this issue ?

**Comment by Shivangi015** [comment]
hey @QAZIMAAZARSHAD can i work on this issue, please assign this to me.
