### ISSUE TITLE
Glowing Pencil loader page

### ISSUE THREAD

**Issue by ankita-104** [QAZIMAAZARSHAD/Movie-Streaming-Website#549]
please assign this to me I want to work on it

**Comment by ankita-104** [comment]
![WhatsApp Image 2022-10-08 at 14 46 31](https://user-images.githubusercontent.com/99471567/194700057-5e96edad-a7fd-4956-83e5-9bec18343b15.jpeg)
here is a screenshot of the animation

**Comment by QAZIMAAZARSHAD** [comment]
@ankita-104 this issue is not required, the preloader is fine.
I thought you opened this issue in my other repository https://github.com/QAZIMAAZARSHAD/Apni-Dukaan.
My mistake.

You can work on this issue in the [Apni Dukaan](https://github.com/QAZIMAAZARSHAD/Apni-Dukaan) project.

**Comment by ankita-104** [comment]
ok so  can I add it to that repo?

**Comment by QAZIMAAZARSHAD** [comment]
> ok so can I add it to that repo?

Yes. 
Go ahead.
