### ISSUE TITLE
Unclear photo

### ISSUE THREAD

**Issue by rajput999** [QAZIMAAZARSHAD/Movie-Streaming-Website#553]
I photo in tv show card is not clear as it is stressed.
I can fix it by making the photo small and in bottom there will be details with background color.
<img width="1404" alt="Screenshot 2022-10-18 at 8 02 47 PM" src="https://user-images.githubusercontent.com/108625391/196462821-d30999e2-9705-4e22-a6b8-70c5dda80799.png">

**Comment by QAZIMAAZARSHAD** [comment]
Make it similar to the cards on the home page.

**Comment by rajput999** [comment]
Okk and thnx

**Comment by rajput999** [comment]
Please @QAZIMAAZARSHAD  Merge my pull request.
