### ISSUE TITLE
Header hover effect

### ISSUE THREAD

**Issue by rajput999** [QAZIMAAZARSHAD/Movie-Streaming-Website#557]
Header without hover effect is very simply. I can give very beautifull hover effect to your header of website.
and i will give the hover effect which will match your design. pls @QAZIMAAZARSHAD assign this work to me.

**Comment by rajput999** [comment]
please @QAZIMAAZARSHAD  merge my pull request

**Comment by Shikhar2702** [comment]
Hey @QAZIMAAZARSHAD 
 i am interested to work on this project can you assign me this issue ?

**Comment by OnaliyVinukiy** [comment]
Hey @QAZIMAAZARSHAD Can you please assign me to this issue. I am interested in working on this

**Comment by OnaliyVinukiy** [comment]
Hey @QAZIMAAZARSHAD I solved this issue and made a pull request. I hope you like it and would accept it
