### ISSUE TITLE
Login page Button Design change

### ISSUE THREAD

**Issue by exotic123567** [QAZIMAAZARSHAD/Movie-Streaming-Website#559]
The Home page has three non-functional buttons below the login button which do nothing on clicking so it'd be better if it is replaced by simple text.
![Not Buttons movies](https://user-images.githubusercontent.com/86504733/197242811-247d7144-986b-4578-b1c0-ac313c21c3d3.JPG)

**Comment by exotic123567** [comment]
Please assign me this task. I can send a PR soon!

**Comment by QAZIMAAZARSHAD** [comment]
They are not buttons, not clickable. Only for design.

If you have a better design idea you can replace it.
