### ISSUE TITLE
Screen Sizing is very improper

### ISSUE THREAD

**Issue by darshjain** [QAZIMAAZARSHAD/Movie-Streaming-Website#58]
The Page overflows a lot in both vertical axis and horizontal axis. Also some content like footer overlaps in some situations

**Comment by QAZIMAAZARSHAD** [comment]
@darshjain these issues are already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/1 and https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/49.

Before opening any issue always make sure that no other similar issue is open.
