### ISSUE TITLE
No close button in login page !

### ISSUE THREAD

**Issue by Nupur19nj** [QAZIMAAZARSHAD/Movie-Streaming-Website#582]
I want to add a closing button in the login page so that if someone wants to exit the page he can.
![image](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/assets/114866308/228ea01d-b4e3-4c52-870f-17b0354c0f71)

Kindly assign me this issue under hacktober accepted! I'll complete it quickly.

**Comment by QAZIMAAZARSHAD** [comment]
Don't think a close button makes sense here, user can navigate to Sign Up page, or if user doesn't want to proceed they can close tab.

**Comment by Nupur19nj** [comment]
But it doesn't get open in new page and if a user closes the tab then your whole website will be closed!

**Comment by QAZIMAAZARSHAD** [comment]
@Nupur19nj where will you put this close button? And the user will be redirected to which page on clicking the close button?

If you think it's a good idea, please go ahead and reopen the issue. I'll merge your changes if the feature enhances the website.

**Comment by Nupur19nj** [comment]
Can you please reopen it and assign me under hacktober-accepted i'll add it quickly then you can merge if you like!

**Comment by Nupur19nj** [comment]
Done with the task!
![image](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/assets/114866308/c93445dc-114d-442a-b1de-d98e10d63b82)
On clicking close button, it takes back to the home page 
![image](https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/assets/114866308/8b53588b-d2d7-44ea-901d-71a868222904)

**Comment by QAZIMAAZARSHAD** [comment]
The little close icon beside the sign-in text doesn't look good. Also, even after skipping the sign-in/sign-up the user is getting access to the entire website, it's not a good use case.
