### ISSUE TITLE
Make navbar fixed

### ISSUE THREAD

**Issue by archanagandhi** [QAZIMAAZARSHAD/Movie-Streaming-Website#59]
hey @QAZIMAAZARSHAD, I would like to make the navbar of the website fixed and sticky on top. Please assign this to me

**Comment by QAZIMAAZARSHAD** [comment]
@archanagandhi this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33.

Before opening any issue always make sure that no other similar issue is open.
