### ISSUE TITLE
Make search bar functional

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#6]
It should filter movies when typing movie names in the search bar.

**Comment by abhijeet141** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
Great,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by abhijeet141** [comment]
@QAZIMAAZARSHAD sir i was having some doubt on this like i have to only work for the filter part or also on search bar button?

**Comment by QAZIMAAZARSHAD** [comment]
You have to make the search bar functional. 
This means that whenever someone enters any movie name in the search bar and presses the search button then that movie card should appear.

This issue did not have anything to do with the styling and design of the search bar or button. It's up to you if you want to improve or work on the design part.

**Comment by abhijeet141** [comment]
@QAZIMAAZARSHAD Sir i mean to say that now the movie cards are not clickable so there is no id defined for respective movie cards so should i wait till this issue got solved or should i make cards for different movie section in this issue only?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, you can do everything in order to resolve this issue.

**Comment by abhijeet141** [comment]
Okay sir

**Comment by WH0SUMIT** [comment]
hello sir, I would also like to contribute to this feature.

**Comment by abhijeet141** [comment]
@QAZIMAAZARSHAD Sir one issue is open for designing description window when movie card is clicked so when that issue will be merged it will be easier to add searchbar , as then by searching the movie name the description window will be popped up or else first we have to add description then add searchbar

**Comment by abhijeet141** [comment]
@QAZIMAAZARSHAD I will start this issue as soon as that issue will be merged :)

**Comment by QAZIMAAZARSHAD** [comment]
Sure

**Comment by KunalSharmaCoder** [comment]
@QAZIMAAZARSHAD sorry for making new project when its already present now please you can assign me this project

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD sorry for making new project when its already present now please you can assign me this project

It is called an issue.
