### ISSUE TITLE
Design a logo that suits UI.

### ISSUE THREAD

**Issue by starrohan999** [QAZIMAAZARSHAD/Movie-Streaming-Website#62]
here it is.
![Apna Theater](https://user-images.githubusercontent.com/71714344/121408703-4d027100-c97e-11eb-8fde-91f4605b7cfb.png)

**Comment by starrohan999** [comment]
we can add in the main page replacing old I guess.

**Comment by starrohan999** [comment]
I am LGM soc-21 participant.

**Comment by Charvi-Bansal** [comment]
I would like to work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@starrohan999, @Charvi-Bansal, and @vishalps2606 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/4.

All of you show your designs in that issue.
And don't make any PR's until I told you to do.
