### ISSUE TITLE
Change the fonts and background

### ISSUE THREAD

**Issue by Nikhita28** [QAZIMAAZARSHAD/Movie-Streaming-Website#63]
The font family of the page can be changed to something more flattering. I would like to change the background of the entire website and instead of a single colour, we can have some gradient or an image whichever looks better.
I would like to work on this under lgmsoc 2021.

**Comment by QAZIMAAZARSHAD** [comment]
@Nikhita28 these issues are already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/20 and https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/19.
Before opening any new issues always make sure that no other similar issue is already open.
You can look for any other issues or open new issues.
