### ISSUE TITLE
Adding space between sections of home page

### ISSUE THREAD

**Issue by drishika2002** [QAZIMAAZARSHAD/Movie-Streaming-Website#65]
I would like to add space between the sections: Movies, Web Series, and Kids that is visible on the home page.

![Screenshot (1527)](https://user-images.githubusercontent.com/76254057/121420356-98228100-c98a-11eb-9eeb-7a1bda04ea8f.png)

Please assign this issue to me under LGM SOC'21.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to add space between the sections: Movies, Web Series, and Kids that is visible on the home page.
> 
> ![Screenshot (1527)](https://user-images.githubusercontent.com/76254057/121420356-98228100-c98a-11eb-9eeb-7a1bda04ea8f.png)
> 
> Please assign this issue to me under LGM SOC'21.

No need @drishika2002.
Also, other issues like carousel view for movie cards, hovering effect, redesign home page are also open this issue will be fixed there.
