### ISSUE TITLE
Footer Redesign

### ISSUE THREAD

**Issue by AKC068** [QAZIMAAZARSHAD/Movie-Streaming-Website#68]
- [ ] I think footer needs modification.
- [ ] It should contain all the info which generally a footer contains.
- [ ] `Suggestion` - There should be a contact form or a new contact page.
> If you agree for new contact page then I'll make separate issue for this.

@QAZIMAAZARSHAD can you please assign this issue to me as participant of LGM-SOC'21 ?

**Comment by QAZIMAAZARSHAD** [comment]
@AKC068 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/5.

Before opening any issue always make sure that no other similar issue is open.

**Comment by AKC068** [comment]
Ohh so sorry I think I haven't seen it.
What about contact page

**Comment by QAZIMAAZARSHAD** [comment]
> Ohh so sorry I think I haven't seen it.
> What about contact page

Okk if you want to create a contact page go ahead.
Open a new issue and I will assign you.
