### ISSUE TITLE
Index Page and Tv Page Improvement

### ISSUE THREAD

**Issue by SanjeevKumar22** [QAZIMAAZARSHAD/Movie-Streaming-Website#69]
Footer changes
Login Page
Responsive

**Comment by QAZIMAAZARSHAD** [comment]
@SanjeevKumar22 these issues are already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/37, https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/5, https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/2.

Before opening any issues always make sure that no other issue is already open.

**Comment by SanjeevKumar22** [comment]
i already made dark and light mode and changed the Tv page Can i make pull request??

**Comment by QAZIMAAZARSHAD** [comment]
@SanjeevKumar22 go to issue number #37 for TV design and issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/22 for dark/light mode.

Ping me in both the issues to assign you that issue then only you can make PR. Also other contributors are already working on these issues so only the best design will be accepted.
