### ISSUE TITLE
Add a stylish pre-loader 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#7]
It will be better if the pre-loader follows a **(red-black)** theme like the website and related to cinema or movies.

**Comment by shivshankar9** [comment]
I would like to work on this, please assign to me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 are you working on this?

**Comment by shivshankar9** [comment]
yes i am working,

**Comment by QAZIMAAZARSHAD** [comment]
It has been 16 days since it was open, do fast

**Comment by shivshankar9** [comment]
yes, late because my exams also going on,
i am trying to fix out this issue...

**Comment by QAZIMAAZARSHAD** [comment]
Okk,

Use some design related to movies, red and black color.
Also, have a look at logos in the Images/Logo folder.

**Comment by shivshankar9** [comment]
i have tried this,
i am facing problems here!!
![Screenshot (12)](https://user-images.githubusercontent.com/69760883/122342982-d8719880-cf62-11eb-8118-9727bf193f7a.png)
![Screenshot (11)](https://user-images.githubusercontent.com/69760883/122343010-de677980-cf62-11eb-992c-599ac3b9783a.png)

**Comment by QAZIMAAZARSHAD** [comment]
Can't understand the issue.

Also, this design doesn't look good.

**Comment by QAZIMAAZARSHAD** [comment]
> Okk,
> 
> Use some design related to movies, red and black color.
> Also, have a look at logos in the Images/Logo folder.

Try this.

**Comment by shivshankar9** [comment]
> > Okk,
> > Use some design related to movies, red and black color.
> > Also, have a look at logos in the Images/Logo folder.
> 
> Try this.

okk

**Comment by nitishapiplani** [comment]
may i work on this

**Comment by shivshankar9** [comment]
> may i work on this

Yes. Ofcourse go ahead,
I'm not able to fix out this

**Comment by QAZIMAAZARSHAD** [comment]
> may i work on this

Try to use website logo design in preloader.

**Comment by nitishapiplani** [comment]
okk

**Comment by nitishapiplani** [comment]
![preloader](https://user-images.githubusercontent.com/83905949/122746961-26aad280-d2a8-11eb-9408-93ca09201c41.PNG)

**Comment by QAZIMAAZARSHAD** [comment]
Nice

**Comment by nitishapiplani** [comment]
so may i continue with this
