### ISSUE TITLE
Create user interest page or quiz

### ISSUE THREAD

**Issue by theSumeetGithub** [QAZIMAAZARSHAD/Movie-Streaming-Website#71]
Can U assign me to these?

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea @theSumeetGithub.

But the login page issue is already open see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/13.

You can create an interest page.
As soon as the user logins, It should direct it to the interest page where the user has to select interested movies among different choices or you can also create a quiz to determine interests then redirect the user to the home page.

**Comment by theSumeetGithub** [comment]
Ohkk I am starting my work

**Comment by Esha-Sherring** [comment]
Can I work in collaboration for this issue ?

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by theSumeetGithub** [comment]
but  @QAZIMAAZARSHAD i  have done it ? my work is just to get end.....

**Comment by theSumeetGithub** [comment]
@Esha-Sherring welcome to team

**Comment by Esha-Sherring** [comment]
> @Esha-Sherring welcome to team

This issue got closed is the work done or I can make a different quiz page?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, this issue has been resolved.
If you want to make any improvements you can open another issue.
