### ISSUE TITLE
problem of logo on hover

### ISSUE THREAD

**Issue by SNEHAL311998** [QAZIMAAZARSHAD/Movie-Streaming-Website#76]
The logo and text move towards the right side on hovering. Pls assign me for this issue

**Comment by QAZIMAAZARSHAD** [comment]
> The logo and text move towards the right side on hovering. Pls assign me for this issue

@SNEHAL311998 this is not a problem this is an effect.
Also, other similar issues like design logo, redesign home page, etc. are also open which will improve the design.
