### ISSUE TITLE
Card Animation and resoponsive to mobile

### ISSUE THREAD

**Issue by SanjeevKumar22** [QAZIMAAZARSHAD/Movie-Streaming-Website#77]
On hovering on movie card in flips and shows description

**Comment by RiyaGupta89** [comment]
May I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
@SanjeevKumar22 and @RiyaGupta89 these issues are already open see issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/3 and https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/2.

Don't open any issue which are already open. Before opening issues always make sure that no other similar issue is open.
