### ISSUE TITLE
Bug in movie categories list

### ISSUE THREAD

**Issue by Ciggzy1312** [QAZIMAAZARSHAD/Movie-Streaming-Website#78]
The Suspense And Thriller category is in separate line although it is considered a single option

I would like to fix this issue under the lgm-soc tag

![image](https://user-images.githubusercontent.com/65884232/121487903-2f6def80-c9f0-11eb-9891-ed91d47776a1.png)

**Comment by QAZIMAAZARSHAD** [comment]
@Ciggzy1312 this issue has already been resolved in issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/12 and will be closed soon.

Please always make sure that no other similar issue is open before opening any new issue.
