### ISSUE TITLE
Update Login UI

### ISSUE THREAD

**Issue by AkhilReddy21** [QAZIMAAZARSHAD/Movie-Streaming-Website#79]
Login page UI is bit clumsy and less attractive.so,I would like to update the UI with some attractive elements using HTML and CSS

**Comment by QAZIMAAZARSHAD** [comment]
@AkhilReddy21 this issue is already open. See issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/13.

Before opening any issue always make sure that no other similar issue is open.
