### ISSUE TITLE
Make slideshow continuous or redesign

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#8]
![WhatsApp Image 2021-06-01 at 6 50 54 PM](https://user-images.githubusercontent.com/56196640/120330452-767e2580-c30a-11eb-858a-2bfea10a4b6d.jpeg)

Eliminate the gap after the slideshow ends.

**Comment by Anupam-Panwar** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
Great,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by nandinimalik16** [comment]
@QAZIMAAZARSHAD  I would like to work on this, please this issue to me

**Comment by nandinimalik16** [comment]
@QAZIMAAZARSHAD  I have created a pull request , please review it tell the necessary changes that I should do
