### ISSUE TITLE
Adjust the movie, web series, and kids pages 

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Movie-Streaming-Website#80]

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Always describe the issue and improvements you want to make whenever you open an issue.
"Adjust the movie, web series, and kids pages" this line is not clear.

Also issues to redesign the home page, design kids and web series page, improve kids, movies section is already open.
Before opening any issues always make sure that no other similar issue is open.
