### ISSUE TITLE
Improve the copyright design

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Movie-Streaming-Website#81]

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure, go ahead.

**Comment by QAZIMAAZARSHAD** [comment]
Use issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/5.

Ping me their and I will assign you.

**Comment by tjanhvi** [comment]
okay :)
