### ISSUE TITLE
Work on slide Holder 

### ISSUE THREAD

**Issue by nandinimalik16** [QAZIMAAZARSHAD/Movie-Streaming-Website#82]
to stop the motion as the mouse hover over any of the movie . also make slider button to rotate in the direction wanted

**Comment by nandinimalik16** [comment]
@QAZIMAAZARSHAD  I would like to work on this issue. Please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea @nandinimalik16.

But use issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/8.
Ping me there and I will assign you.
