### ISSUE TITLE
Search bar feature

### ISSUE THREAD

**Issue by WH0SUMIT** [QAZIMAAZARSHAD/Movie-Streaming-Website#83]
hello sir, 
I would like to contribute to this feature, Basically in this feature whenever the user type for any movie name it will automatically show the modal popup box with the movie image & name if there is any movie present with that name and if there is no such movie is present then it will show an alert box/popup box with a message that no such movie is present and try again !!

**Comment by QAZIMAAZARSHAD** [comment]
@WH0SUMIT this issue is already open, see issue number #6.

You can contribute to that issue. Ping me there to assign you.
