### ISSUE TITLE
Design contact page

### ISSUE THREAD

**Issue by AKC068** [QAZIMAAZARSHAD/Movie-Streaming-Website#88]
>  An important part for this kind of website so that user can easily reach you out for their issues and feedback.

@QAZIMAAZARSHAD I would like to work on this as participant of LGM-SOC'21. Please assign this to me.

**Comment by ekagrashukla** [comment]
HI! As a participant of LGM SOC21, I'd like to work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Remember, since many contributors are working on this issue, the best design will be accepted.

**Comment by harshita0802goswami** [comment]
Hii!! Pls assign this issue to me

**Comment by tanzzz-tech** [comment]
Please assign this issue to me! i am a LGMSOC participant

**Comment by AKC068** [comment]
@QAZIMAAZARSHAD sorry but I haven't given my pr yet then how it can be closed.
2nd I have created the pr.
And you told best will be merged.
As now it is closed so how can I send pr ?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD sorry but I haven't given my pr yet then how it can be closed.
> 2nd I have created the pr.
> And you told best will be merged.
> As now it is closed so how can I send pr ?

Yes, I know.

If you believe your design is better, then you can again open a new issue "Improve contact page" ask me to assign you that issue then make your PR.

**Comment by AKC068** [comment]
ok
