### ISSUE TITLE
Add logo in title bar

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Movie-Streaming-Website#9]
![image](https://user-images.githubusercontent.com/56196640/120331108-10de6900-c30b-11eb-88a1-c708eae510f5.png)

**Comment by JAsaxon** [comment]
ill work on this, what logo should I add?

**Comment by QAZIMAAZARSHAD** [comment]
If you want you can design a new logo this issue is also open (https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/4) you can work on both issues
If you don't want to design a new logo you can add the existing logo or any good movie symbol.

But don't start working on any issue, make sure you are assigned to that issue.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
@Jagannath8 one participant has already asked to work on this issue.
Since this is a very basic and simple issue I cannot allow more than one person to work on it.

You can work on issue number https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/4

**Comment by ish-0709** [comment]
Sir if this issue is still unresolved, Can I work on this issue?

**Comment by marizvi** [comment]
Can you please assign this issue to me..

**Comment by QAZIMAAZARSHAD** [comment]
@JAsaxon are you working on this issue or should I unassign you?

**Comment by prads46** [comment]
sir if this issue is still unresolved will u please assign this  issue to me?

**Comment by QAZIMAAZARSHAD** [comment]
@Jagannath8 use this pic -> https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/blob/master/Images/Logo/Title.jpeg.

**Comment by QAZIMAAZARSHAD** [comment]
> sir if this issue is still unresolved will u please assign this issue to me?

@prads46 others have asked prior to you they are first in line.

Look for any other issue.

**Comment by QAZIMAAZARSHAD** [comment]
@Jagannath8 are you working on this?

**Comment by Jagannath8** [comment]
yes

**Comment by QAZIMAAZARSHAD** [comment]
> yes

Fine
