### ISSUE TITLE
Design Header Structure and design

### ISSUE THREAD

**Issue by vimalprogrammer** [QAZIMAAZARSHAD/Movie-Streaming-Website#92]
Align the header icons correctly and make opacity effects in header icons

Reference below...
![WhatsApp Image 2021-06-10 at 11 17 46 PM](https://user-images.githubusercontent.com/76787061/121573143-86041980-ca42-11eb-9a86-c9947e145ea8.jpeg)

I would like to work on this issue under LGMSOC, please assign me...

**Comment by QAZIMAAZARSHAD** [comment]
@vimalprogrammer this issue is already open https://github.com/QAZIMAAZARSHAD/Movie-Streaming-Website/issues/33.

Before opening any issue always make sure that no other similar issue is open.
