### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by starrohan999** [QAZIMAAZARSHAD/Movie-Streaming-Website#93]
In the footer section, the year is not updated.

**Comment by AnjaniSriya** [comment]
I an a member of LGM SOC
Please allow me, I can do this

**Comment by QAZIMAAZARSHAD** [comment]
> please assign it to me @QAZIMAAZARSHAD

Don't just change the text.
It should update automatically every year according to date.

**Comment by QAZIMAAZARSHAD** [comment]
> I an a member of LGM SOC
> Please allow me, I can do this

@AnjaniSriya this issue has already been assigned look for some other issues.

**Comment by MEETOZA123** [comment]
hello sir can i work on this issue
please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
> hello sir can i work on this issue
> please assign it to me

@MEETOZA123 this issue has already been assigned look for some other issues.

**Comment by starrohan999** [comment]
Thank you for assign this task to me.
I will make Pr in next 30 min.

**Comment by MathurUtkarsh** [comment]
Hello I had worked on this issue 
Please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Hello I had worked on this issue
> Please assign it to me.

Already resolved. Will be closed soon.
